### ISSUE TITLE
Clicking on select icon doesn't open select

### ISSUE THREAD

**Issue by henriollik** [Dogfalo/materialize#1004]
This one is quite simple - if you click on the arrow suffix icon on the select element, it doesn't actually engage the given element. I've also found the optimal fix to be to just set the icon's z-index to -1.

```css
.select-wrapper .mdi-navigation-arrow-drop-down {
  position: absolute;
  right: 0;
  top: 0;
  font-size: 23px;

  z-index: -1;
}
```
