### ISSUE TITLE
[Helpers] Responsive alignment

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#1011]
```css
.l-center-align
{
    text-align: center;
}

.l-left-align
{
    text-align: left;
}

.l-right-align
{
    text-align: right;
}

@media only screen and (max-width : 992px) 
{
    .m-center-align
    {
        text-align: center;
    }
    
    .m-left-align
    {
        text-align: left;
    }
    
    .m-right-align
    {
        text-align: right;
    }
}

@media only screen and (max-width : 600px) 
{
    .s-center-align
    {
        text-align: center;
    }
    
    .s-left-align
    {
        text-align: left;
    }
    
    .s-right-align
    {
        text-align: right;
    }
}
```
