### ISSUE TITLE
SideNav appears darkened

### ISSUE THREAD

**Issue by hexturtle** [Dogfalo/materialize#1030]
Following up from issue #1028, the remaining issue is the SideNav remains darkened when I apply the following css to `<nav>`:

```css
nav {
    position: relative;
    z-index: 1;
    overflow: visible;
}
```

Increasing the `z-index` on `<nav>` to 998+ allows for both the SideNav and the top navbar to not be darkened when the SideNav is out. However, the correct behavior is for the top navbar to be darkened while the SideNav is not darkened when the SideNav is pulled out.

What workaround is there for this issue?

**Comment by Dogfalo** [comment]
You have to move the `<ul id="slide-out">` out from within the fixed nav HTML structure

**Comment by hexturtle** [comment]
Great, thanks. This solution is working well, and without needing to include the `overflow: visible`. Unfortunately, the styling gets lost for the sidebar links, but I'll just have to go dig that up.

**Comment by Dogfalo** [comment]
Add
```CSS
  .side-nav li a {
    color: #444;
    display: block;
    font-size: 1rem;
    height: 64px;
    line-height: 64px;
    padding: 0 15px;
  }
```
