### ISSUE TITLE
Buttons with color styles partially lose hover effect

### ISSUE THREAD

**Issue by hexturtle** [Dogfalo/materialize#1035]
Consider this button:

```html
<a id="event-submit" class="waves-effect waves-light btn-large indigo lighten-3 col s11">Button</a>
```

Placing this button just in the `<body>` (as well as other places) results in a button that does not have the lighten hover effect. In other words, upon hovering over it, the button will take on an additional shadow but will not have the lighten effect the default button without color styling has.

Is there a way to fix this?

**Comment by Dogfalo** [comment]
You can add back the :hover style manually, or

```CSS
.btn {
  overflow: hidden;
}
.btn:hover:before {
  opacity:1;
}

.btn:before {
    content: '';
    opacity: 0;
    background-color: rgba(0,0,0,.6);
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
    transition: opacity .2s;
    z-index: -1;
}
```
