### ISSUE TITLE
Styling SideNav Links

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1060]
```display:block``` is not added automatically to SideNav links so that one must click on the text in order to activate the link:
```css
ul.side-nav a {
    display: block;
}
```
