### ISSUE TITLE
How to change the color of blockquote ?

### ISSUE THREAD

**Issue by chaosink** [Dogfalo/materialize#1122]
It seems that `blockquote` can only be pink.

**Comment by tmd-uk** [comment]
You just need to change it in your css file like this: 

```css
blockquote{
  margin: 20px 0;
  padding-left: 1.5rem;
  border-left: 5px solid #64b5f6; /* Just change the color value and that's it*/
}
```
And it should look like this: http://codepen.io/tmd-uk/pen/JoqzaX
