### ISSUE TITLE
Avatars are broken in collection with header

### ISSUE THREAD

**Issue by limitium** [Dogfalo/materialize#1307]
```html
<ul class="collection with-header">
        <li class="collection-header">
            <h4>azazazaza</h4>
        </li>
        <li class="collection-item avatar">
            <img ng-src="http://lorempixel.com/200/200/nightlife/" alt="" class="circle">
            <span class="title">Title</span>
            <p>First Line <br>
                Second Line
            </p>
            <a href="#!" class="secondary-content"><i class="mdi-action-grade"></i></a>
        </li>
    </ul>
```

avatar padding rule
```css
.collection .collection-item.avatar {
  height: 84px;
  padding-left: 72px;
  position: relative;
}
```
is overwritten by
```css
.collection.with-header .collection-item {
  padding-left: 30px;
}
```
