### ISSUE TITLE
Avatar overlapping item title in collection with header

### ISSUE THREAD

**Issue by adamdawkins** [Dogfalo/materialize#1336]
There seems to be a CSS override issue cause by using `.collection.with-header` and `.collection-item.avatar`, which cause the padding-left for the `.collection-item` to be set incorrectly. The problem is that the item title overlaps the avatar.

Code Pen: http://codepen.io/anon/pen/MwKrGm

![screen shot 2015-05-10 at 22 10 08](https://cloud.githubusercontent.com/assets/27672/7556282/428e09b8-f762-11e4-9436-231739fc9aa4.png)

The CSS in the Inspector shows what's going on quite clearly, but I can't find the line in the SASS to contribute a pull request (sorry!):

```css

.collection .collection-item.avatar {
  ...
  padding-left: 72px;
}

/* this overrides  the 72px above and sets the padding-left */
.collection.with-header .collection-item {
  padding-left: 30px;
}
```

Both rules have the same specificity, so I would assume this is some sort of write-order issue.
