### ISSUE TITLE
Local hosted icons

### ISSUE THREAD

**Issue by ajcarranquinha** [Dogfalo/materialize#1388]
I'm creating an app with your framework, the app will be used on a local network only.
I have an issue ... i'm unable to load material-design-icon on IOS browsers(testes on Ipad 2 Mini - Mobile Safari 8 and Chrome) and stock Android browsers (test on Samsung Galaxy Tab 4 Android 4.4.2 but it works without problem on Chrome)

**Comment by Dogfalo** [comment]
don't know, could be a server issue. But either way, the icons have been tested on android stock browsers.

**Comment by JoachimR** [comment]
I host the icons locally by putting them into the client app assets.

Download https://fonts.gstatic.com/s/materialicons/v7/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2
and put it in your client web app folder somewhere and then reference it in your CSS like that:

In your index.html

```html
<head>
<!-- ...... -->
<style type="text/css">

        /**
         * instead of linking from https://fonts.googleapis.com/icon?family=Material+Icons
         */

        @font-face {
            font-family: 'Material Icons';
            font-style: normal;
            font-weight: 400;
            src: local('Material Icons'), local('MaterialIcons-Regular'), url(assets/fonts/materialicons.woff2) format('woff2');
        }

        .material-icons {
            font-family: 'Material Icons';
            font-weight: normal;
            font-style: normal;
            font-size: 24px;
            line-height: 1;
            letter-spacing: normal;
            text-transform: none;
            display: inline-block;
            word-wrap: normal;
            -webkit-font-feature-settings: 'liga';
            -webkit-font-smoothing: antialiased;
        }

    </style>

<!-- ...... -->
</head>
```

**Comment by JoachimR** [comment]
1. Download the woff and woff2 file . When you open
https://fonts.googleapis.com/icon?family=Material+Icons
you see that the url(...) tag
copy the URL and open it in chrome/firefox for getting the woff2 file
copy the URL and open it in IE for getting the woff file

2. Save the woff and woff2 file to your web app, for example the folder assets/fonts/

3. Add to your CSS:

```scss
/**
* instead of linking from https://fonts.googleapis.com/icon?family=Material+Icons
*/
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'),
  url(../assets/fonts/materialicons.woff2) format('woff2'),
  url('../assets/fonts/materialicons.woff') format('woff');
}
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  word-wrap: normal;

  font-feature-settings: 'liga'; // !!! make sure this is set !!!
  -webkit-font-feature-settings: 'liga';  
  -webkit-font-smoothing: antialiased;
}
```
