### ISSUE TITLE
MeteorJS + Sass - Icons missing and Waves messing

### ISSUE THREAD

**Issue by pistou** [Dogfalo/materialize#1430]
I have multiple issues with the **Sass Sources** (v0.96.1) downloaded from your website.
I use it in a meteor project, but **icons are not showing** and **waves doesn't display the right color at the end of the animation**

Here's the different steps:
- Create and run a Meteor project and add fourseven:scss package to compile Sass files

``` Console
meteor create debug
cd debug
meteor add fourseven:scss
meteor
```
- Add a `client` folder and paste Materialize Sass sources
- Edit `debug.html` to add buttons

``` HTML
<head>
  <title>debug</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
    <a class="waves-effect waves-light btn">Stuff</a>
    <a class="waves-effect waves-light btn"><i class="mdi-file-cloud left"></i>button</a>
    <a class="waves-effect waves-light btn"><i class="mdi-file-cloud right"></i>button</a>
    <a class="btn-floating btn-large waves-effect waves-light red"><i class="mdi-content-add"></i></a>
</template>
```

Here is a screenshot of the result, **once I clicked the middle button**
![debug](https://cloud.githubusercontent.com/assets/6703711/7816076/7a472364-03cc-11e5-9ddd-6a05c891d23b.jpg)

---

Note that adding Materialize via `meteor add materialize:materialize` works very well.

But then, you can't access to the sources and play with the `_color.scss` and `_variables.scss` files - which I need to.
It is the best way I found until #1018

**Comment by alfv89** [comment]
The problem is in file _icons-material-design.scss.

The font's code in content property is being compiled without quotes.

```sass
@function unicode($str){
  @return unquote("\"") + $str + unquote("\"");
}

@each $mdi-icon-name, $mdi-icon-value in $mdi-list-icons {
  .#{$mdi-prefix}#{$mdi-icon-name}:before {
    content: unicode($mdi-icon-value);
  }
}
```

part of the compiled css:
```css
.mdi-action-3d-rotation:before {
  content: ; }

.mdi-action-accessibility:before {
  content: ; }

.mdi-action-account-balance:before {
  content: ; }

.mdi-action-account-balance-wallet:before {
  content: ; }

.mdi-action-account-box:before {
  content: ; }
```

**Comment by nowke** [comment]
I faced the same issue.

I replaced
```scss
@each $mdi-icon-name, $mdi-icon-value in $mdi-list-icons {
  .#{$mdi-prefix}#{$mdi-icon-name}:before {
   content: unicode($mdi-icon-value);
  }
}
```
by,
```scss
@each $mdi-icon-name, $mdi-icon-value in $mdi-list-icons {
  .#{$mdi-prefix}#{$mdi-icon-name}:before {
    content: "\"" + $mdi-icon-value + "\"";
  }
}
```

Worked!

**Comment by ShashankaNataraj** [comment]
Can you people please make a PR?

**Comment by mihaerzen** [comment]
Had the same problem, @nowke solution worked for me.

**Comment by RichardLindhout** [comment]
@nowke worked +1, BTW: I think the developers have an older version where this bug isn't fixed. As written in the comments: // remove after bug fix sass 3.3.x and add quote in $mdi-list-icons: ( 'foo': \exxx )

**Comment by gnicol-bzh** [comment]
Same problem with Sass. Tested @nowoke solution and it's ok. Thank you!

**Comment by Jehu** [comment]
@ShashankaNataraj would make a PR, but can't find this code in master branch:
```scss
@each $mdi-icon-name, $mdi-icon-value in $mdi-list-icons {
  .#{$mdi-prefix}#{$mdi-icon-name}:before {
    content: unicode($mdi-icon-value);
  }
}
```

Any idea?
