### ISSUE TITLE
Allow optional "x" to dismiss toast messages.

### ISSUE THREAD

**Issue by GloverDonovan** [Dogfalo/materialize#1453]
Continuing the discussion from #1389.

The Problem:  Many users aren't aware that they can close the toast messages by swiping on it. This is apparent especially on **Desktop** devices where the user is not accustomed to swiping.

Here is a more recent complaint on the Gitter board: https://gitter.im/Dogfalo/materialize?at=5568b4cfa891bec12ef4d221

---

The solution: Provide the user with some hint on how to close the modal.

I am in favor of two options, although I do prefer the latter.
- Make the click event close the message (This would work, but it may cause some unexpected closes; this may not be the ideal option since the problem of the user not knowing that it's closable still exists until the user clicks/taps the message).
- Add an "x" button to the message (This is ideal since the user will immediately **know** that they have the option to manually close the modal).

Refer to the docs for the current method of dismissing notifications: http://materializecss.com/dialogs.html

I'm not saying that the swiping method be replaced with one of these options; it's the opposite, actually. By adding the "x" to the message, it triggers an instinct in users that the toast message **is  indeed closable**, something that is _not_ apparent in the current setting.

cc: @jcapogna @acburst @mdcsfk @Dogfalo

**Comment by jcapogna** [comment]
I vote for adding an an X close. The mechanism I mentioned in #1389 has been very well received by people I've showed it to.

**Comment by koustuvsinha** [comment]
Modals should also have an "X" to close, with respective options and callbacks

**Comment by gizotti** [comment]
:+1:

**Comment by rapito** [comment]
+1

**Comment by nrozic** [comment]
:+1:

**Comment by davidbielik** [comment]
If anyone's interested in a quick easy workaround:
```
$(document).on('click', '#toast-container .toast', function() {
    $(this).fadeOut(function(){
        $(this).remove();
    });
});
```

**Comment by artus9033** [comment]
+1

**Comment by flexbrane** [comment]
@davidbielik in addition, you can add this css:

```css
#toast-container .toast::after {
	font-family: 'Material Icons';
	content: "close";
	-webkit-font-feature-settings: 'liga';
	color: #dd2c00;
    font-size: 1.5rem;
	font-weight: 300;
    float: right;
	padding-left: 3rem;
}
```

![image](https://cloud.githubusercontent.com/assets/14235706/19343895/6fee200c-9138-11e6-9b2f-298622801253.png)


### Complete code
**HTML File**
```javascript
<script>
$(document).on('click', '#toast-container .toast', function() {
    $(this).fadeOut(function(){
        $(this).remove();
    });
});
</script>
```

**CSS File**
```css
#toast-container .toast {
    cursor: pointer;
}
#toast-container .toast::after {
	font-family: 'Material Icons';
	content: "close";
	-webkit-font-feature-settings: 'liga';
	color: #dd2c00;
    font-size: 1.5rem;
	font-weight: 300;
    float: right;
	padding-left: 3rem;
}
```
