### ISSUE TITLE
change color radio input

### ISSUE THREAD

**Issue by Artessan** [Dogfalo/materialize#1507]
Hey! i wanna  know if it's possible change the color of input radio whit external css file. or how know with  sass downloading materialize which  variable change

thanks for the help

**Comment by Artessan** [comment]
hey! I already solved!
Thanks anyway!

**Comment by adenta** [comment]
What did you do?  I cannot find a reliable way to switch checkbox colors.

**Comment by Artessan** [comment]
[type="radio"].with-gap:checked + label:before {
  border-radius: 50%;
  border: 2px solid #0277bd; }

[type="radio"].with-gap:checked + label:after {
  border-radius: 50%;
  border: 2px solid #0277bd;
  background-color: #0277bd;
  z-index: 0;
  -webkit-transform: scale(.5);
  -moz-transform: scale(.5);
  -ms-transform: scale(.5);
  -o-transform: scale(.5);
  transform: scale(.5); }

**Comment by rhroyston** [comment]
[type="radio"]:checked+label:after,
[type="radio"].with-gap:checked+label:before,
[type="radio"].with-gap:checked+label:after {
    border: 2px solid black !important;
}

[type="radio"]:checked+label:after,
[type="radio"].with-gap:checked+label:after {
    background-color: #424242 !important;
    z-index: 0
}

**Comment by abraaoz** [comment]
If you're using Less, you could use this mixin:
```less
.radio-color(@border-color, @background-color: @border-color, @border-color-checked: @border-color) {
	[type="radio"].with-gap {
		&+label:before,
		&+label:after {
			border: 2px solid @border-color !important;
		}
		&:checked+label:before,
		&:checked+label:after {
			border: 2px solid @border-color-checked !important;
		}
		&:checked+label:after {
			background-color: @background-color !important;
		}
	}
}
```
