### ISSUE TITLE
Column-count, cards don't appear

### ISSUE THREAD

**Issue by clerixmaxime** [Dogfalo/materialize#1680]
Hi, 

I would like to create a pinterest-like social hub and I use Materialize cards to put my social media. I would like to have more than 1 column, so I use the css-property column-count as the following : 

```
        #wrapper {
            -webkit-column-count: 3;
            -webkit-column-gap: 10px;
            -webkit-column-fill: auto;
            -moz-column-count: 3;
            -moz-column-gap: 10px;
            -moz-column-fill: auto;
            column-count: 3;
            column-gap: 15px;
            column-fill: auto;

            width:100%;
        }
```

But when I display my content, only cards on the first columns are displayed. My cards are defined like this : 

```
<div class="card">
	<div class="card-image">
      <img src="{{ url }}">
    </div>
    <div class="card-content">
    	<span>{{ username }}</span>
     	<p> {{ message}} </p>
    </div>
</div>
```

I won't use row and col because I don't want to have space between my cards if they don't have the same size. You can see a preview below.

<img width="1167" alt="screen shot 2015-07-06 at 14 15 58" src="https://cloud.githubusercontent.com/assets/7253420/8522856/a0bb12fc-23e9-11e5-9c41-4fedfd0485aa.png">

**Comment by truenorth** [comment]
There are a bunch of gotchas you need to worry about when dealing with CSS3 columns. I've made you a working example since this is a nice pattern to follow (**as long as you don't care about IE9**)

Key points:

### Non-breaking cards

This CSS prevents cards from being "broken". `inline-block` allows the cards to flow as if they're on a single line, and single lines cannot be split across multiple columns.
```css
.cards-container {
   column-break-inside: avoid;
   .card {
       display: inline-block;
   }
}
```

### Responsive columns
You may want your columns to collapse responsively. The following will give you the same effect as if you had something like

```html
<div class="col l4 m6 s12">
   <div class="card">
      ...
   </div>
</div>
```

```scss
@mixin column-count($ct) {
  -webkit-column-count: $ct;
  -moz-column-count: $ct;
  column-count: $ct;
}


@media #{$small-and-down} {
  .cards-container {
    @include column-count(1);
  }
}
@media #{$medium-and-up} {
  .cards-container {
    @include column-count(2);
  }
}
@media #{$large-and-up} {
  .cards-container {
    @include column-count(3);
  }
}
```

### The working example

[(click to visit it)
 ![screen shot 2015-07-06 at 11 39 51 am](https://cloud.githubusercontent.com/assets/558005/8530105/c5fbb38e-23d3-11e5-8b03-9d3746bfb338.png)](http://codepen.io/TrueNorth/pen/MwVoYp?editors=010)
