### ISSUE TITLE
Responsively hiding prefix icons in forms is buggy

### ISSUE THREAD

**Issue by sushruth** [Dogfalo/materialize#1715]
Applying any of the `.hide-*` classes to `.prefix` in an input field are resulting in buggy UI. Properties `margin-left` and `width:calc(100% - 3rem)` of the inputs and/or labels leave empty space in the place of icon.

![screenshot from 2015-07-10 16 35 05](https://cloud.githubusercontent.com/assets/2114206/8629553/db8bb39c-2721-11e5-82ec-9736dca6cd72.png)

**Comment by acburst** [comment]
Can you post a simple codepen to demonstrate the issue? it would help us identify the problems more quickly.

**Comment by sushruth** [comment]
@acburst This should help explain the problem: http://codepen.io/sushruth/pen/NqMVXE . Try resizing the window.

**Comment by DanielRuf** [comment]
```CSS
@media only screen and (max-width: 992px){
  .input-field .prefix.hide-on-med-and-down ~ label,
  .input-field .prefix.hide-on-med-and-down ~ input {
    margin-left:0;
  }
  .input-field .prefix.hide-on-med-and-down ~ input{
    width: 100%;
  }
}
```
