### ISSUE TITLE
animation and icons is not working

### ISSUE THREAD

**Issue by dimonleonov** [Dogfalo/materialize#1802]
In Android 4.2.2 animation in checkboxes and switches not working.
In PC greatly working.
See screenshot
<img src="http://files.zagruzi.16mb.com/m2.jpg">

This a Google Icons...
<img src="http://files.zagruzi.16mb.com/m1.jpg">

<font color="gray"><I>sorry from message in status bar</I></font>

Regards, dimonleonov

**Comment by carlosperate** [comment]
It looks like support for Android below 4.4 is rather limited: https://github.com/Dogfalo/materialize/issues/868

In terms of the icons, Materialize is only importing them from google: https://github.com/Dogfalo/materialize/issues/1711
Might be a good idea to keep an eye on this: https://github.com/google/material-design-icons/issues/180

**Comment by dimonleonov** [comment]
Thanks

**Comment by afermon** [comment]
Hi, @dimonleonov . I had the same issue with material css in android 5.0.1 browser. But I took a look at https://www.google.com/design/icons/   and it does work on the android browser. So when you load the Material icons from Google Fonts  the default css looks different from the one in that page.

Those are the css styles used in the icons page. I just load the material icons from google Fonts and then I added this styles to override the ones that come with google fonts css.
Now they are working correctly with materialcss (At least icons, I haven't test animations).
I hope you find it useful!
```css
material-icons {
    font-family: 'Material Icons';
    text-rendering: optimizeLegibility;
    font-feature-settings: "liga" 1;
    font-style: normal;
    text-transform: none;
    line-height: 1;
    font-size: 24px;
    width: 24px;
    height: 24px;
    display: inline-block;
    overflow: hidden;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```
btw: I don't know why materialcss load the material icons from Google Fonts and the load them too from folder fonts to use as part of the components.
