### ISSUE TITLE
Improve Icon Positioning for Small Devices

### ISSUE THREAD

**Issue by mncaribou** [Dogfalo/materialize#1857]
For nav side bars and icons used in the top men (like a persistent hamburger), noticed when going to a small format, some of the font sizes will adjust with the line height, causing the inset/floated icons to shift up.  This can be fixed by making the following modification to the CSS

nav .nav-wrapper i {
    line-height: inherit;
}

**Comment by FelipeRosa** [comment]
I had the same problem here also in side-nav, dropdowns and pretty much everywhere. I fixed the same way you did
```css
i.material-icons {
    linhe-height: inherit;
    height: inherit;
}
```

I don't know the best place to make this modification to materialize, but on my project a global rule like that works great.

**Comment by DarwinDLRD** [comment]
This icons using Google?

**Comment by akigupta131** [comment]
Following solved my problem:-
```css
i.material-icons {
    line-height: inherit;
    height: inherit;
    vertical-align: middle;
}
```

But it would be great if Materialize team include that too.
