### ISSUE TITLE
Preloader spinner looks strange in Safari

### ISSUE THREAD

**Issue by ramunasm** [Dogfalo/materialize#188]
![preloader](https://cloud.githubusercontent.com/assets/1158178/5299072/c612f018-7bcb-11e4-99aa-1930c5527640.png)
Using Safari on OS X 10.10.1 The circle is not entirely round.
It looks like a bit of the circle is getting cut off?
Works just fine in Chrome.

**Comment by jnthas** [comment]
The same issue occurs in old versions of Firefox (v32)
![firefox-error](https://cloud.githubusercontent.com/assets/7151022/6600595/53250f30-c7ef-11e4-8222-18236973a979.png)

It seems that grey square is a little bit smaller than circle:
![error-firefox-bg](https://cloud.githubusercontent.com/assets/7151022/6600628/870ba610-c7ef-11e4-9b56-9283a72edc82.png)


It works fine on version 36!

**Comment by brendanbates89** [comment]
Not sure what evidence I can provide, but this behavior also happens on the latest Chrome versions if zoom is set to "80%" or "70%", for example.  You can actually just go to [the preloader example page](http://materializecss.com/preloader.html) and set the zoom - you can see the circles become choppy and appear clipped on certain sides.

**Comment by DanielRuf** [comment]
Can you try setting

```CSS
.preloader-wrapper {
    display: inline-block;
    position: relative;
    width: 50px;
    height: 50px;
}
```

instead of

```CSS
.preloader-wrapper {
    display: inline-block;
    position: relative;
    width: 48px;
    height: 48px;
}
```

There might be issues due to the rounding of float values. If you do not set it to 50, the boxes have values like 42.969. These are rounding issues.
48px: 
![image](https://cloud.githubusercontent.com/assets/827205/24475974/ff007b56-14d1-11e7-80c2-3bbcc9b99bc5.png)

50px:
![image](https://cloud.githubusercontent.com/assets/827205/24475999/168b2eec-14d2-11e7-9185-c615f613a04a.png)
