### ISSUE TITLE
sticky-footer with meteor + blaze-layout

### ISSUE THREAD

**Issue by 100ideas** [Dogfalo/materialize#1903]
Just a public service announcement: **If** you are using materializecss + meteor + flowrouter + blaze-layout, sticky-footer will not work out-of-the-box because

> By default, BlazeLayout render layouts into a DOM element with the id __blaze-root

leading to html that looks like

``` html
<body>
  <div id="__blaze-root">
    <header>...
    <main>...
    <footer>...
  </div>
</body>
```

Fix with css like so:

``` css
#__blaze-root {
    display: flex;
  min-height: 100vh;
  flex-direction: column;
}
```

or with javascript: call `BlazeLayout.setRoot('body')` in client js. [Docs](https://github.com/kadirahq/blaze-layout#set-different-root-node). 

Question: why does the intermediate `#__blaze-root` div break the flex layout?
