### ISSUE TITLE
textarea padding too large

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1912]
Setting `padding: 1.6rem` to prevent the text inside textareas from jumping results in bad design, the label above will get too high and the line below too far... Hope there could be a better workaround...

Check: https://github.com/Dogfalo/materialize/blob/v0.97.0/sass/components/_form.scss#L219

``` css
textarea.materialize-textarea {
    padding: 1.6rem 0; /* prevents text jump on Enter keypress */
}
```
