### ISSUE TITLE
webkit: file upload button not completely cursor pointer 

### ISSUE THREAD

**Issue by fabyeah** [Dogfalo/materialize#1930]
Check with chrome on materializecss.com/forms.html, hover mouse over file upload button. Only the bottom area of the button shows the pointer cursor, the text overlays the button at the top.

To fix this, add this:

```
.file-field input[type=file]::-webkit-file-upload-button {
  display: none;
}
```

**Comment by adriendlph** [comment]
Great tip @fabyeah, thank you ;-)

**Comment by kmmbvnr** [comment]
Still not fixed.

Here is the video demo - https://share.viewedit.com/aDEkxpHY27Yn3E5K9a6xCc

**Comment by DanielRuf** [comment]
Please test the following code

```CSS
.file-field input[type=file]  {
    text-indent: -999px;
}

.file-field .btn, .file-field .btn-large {
    position: relative;
    overflow: hidden;
}
```
