### ISSUE TITLE
[Patch]Wrong position of badge in Navbar

### ISSUE THREAD

**Issue by chi-bd** [Dogfalo/materialize#1972]
When we add a badge to link in the Navbar, it will be displayed in the wrong place.

Wrong(original): https://jsfiddle.net/Lcgjvqgq/1/embedded/result/
Fixed(with patch): https://jsfiddle.net/Lcgjvqgq/3/embedded/result/
```CSS
nav ul a span.badge {
    position: initial;
}
```
