### ISSUE TITLE
How to use it when you cannot connect to fonts.googleapis.com?

### ISSUE THREAD

**Issue by penghuajun** [Dogfalo/materialize#2232]
fonts.googleapis.com in China is very slow, the localization of it? Like Awesomeg Font.

**Comment by phatly27** [comment]
Hi penghuajun,

You can download it and font .woff (http://fonts.gstatic.com/s/materialicons/v8/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) back to your local machine. Then include them into your project.

Regards.

**Comment by penghuajun** [comment]
My project structure is
 MyWebsite/
  |--css/
  |  |--materialize.css
  |
  |--font/
  |  |--material-design-icons/
  |  |--roboto/
  |
  |--js/
  |  |--materialize.js
  |
  |--index.html
There is a default file in the default project.
@font-face {
  font-family: "Material-Design-Icons";
  src: url("../font/material-design-icons/Material-Design-Icons.eot?#iefix") format("embedded-opentype"), url("../font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), url("../font/material-design-icons/Material-Design-Icons.woff") format("woff"), url("../font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), url("../font/material-design-icons/Material-Design-Icons.svg#Material-Design-Icons") format("svg");
  font-weight: normal;
  font-style: normal; }
Where did I go wrong?

**Comment by penghuajun** [comment]
HTML structure
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    
    <meta name="renderer" content="webkit">
    
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    
    <meta content="no-archive" name="robots" />
    <title>产品页布局学习</title>
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/style.css">
    
    <script src="js/jquery-2.1.1.min.js"></script>
    <script src="js/materialize.min.js"></script>
</head>

**Comment by penghuajun** [comment]
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    
    <meta name="renderer" content="webkit">
    
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    
    <meta content="no-archive" name="robots" />
    <title>产品页布局学习</title>
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/style.css">
    
    <script src="js/jquery-2.1.1.min.js"></script>
    <script src="js/materialize.min.js"></script>

**Comment by phatly27** [comment]
Assume that the material-icons.css under css folder contains the following content:

```css
@font-face {
font-family: "Material-Design-Icons";
src: url("../font/material-design-icons/Material-Design-Icons.eot?#iefix") format("embedded-opentype"), url("../font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), url("../font/material-design-icons/Material-Design-Icons.woff") format("woff"), url("../font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), url("../font/material-design-icons/Material-Design-Icons.svg#Material-Design-Icons") format("svg");
font-weight: normal;
font-style: normal; }

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

You should include it before css/materialize.min.css.
