### ISSUE TITLE
Background color of Table specified both Highlight and Striped

### ISSUE THREAD

**Issue by chi-bd** [Dogfalo/materialize#2262]
When we add both "highlight" and "striped" class to the table tag, the odd row's background color is the same(#f2f2f2).
The highlight color should be changed, such as #eee.

**Comment by remzr7** [comment]
How would we specify the striped color?

**Comment by chi-bd** [comment]
Like this.
```css
table.highlight tbody tr:hover {
    background-color: #eee !important;
}
```
