### ISSUE TITLE
Offset not working with v0.97.3

### ISSUE THREAD

**Issue by CurosMJ** [Dogfalo/materialize#2323]
The following works with 0.97.2, but the effect of offset is lost when using 0.97.3.
``` html
 <div class="container">
        <div class="row">
            <div class="col m8 offset-m2">
                <div class="card-panel">
                    <h4>Register</h4>
                    <!-- Stuff here -->
                </div>
            </div>
        </div>
    </div>
```
The corresponding CSS :

``` css
.row .col.m8 {
    width: 66.66667%;
    margin-left: 0; // This line is new in 0.97.3
}
```
