### ISSUE TITLE
Bad label looking, if data-error is used

### ISSUE THREAD

**Issue by Messier82** [Dogfalo/materialize#2360]
Hello! Here's my problem: if I place input boxes under each other it looks nice, but only until I enter some error message label and then focus on below label. Here's an example:
![wrong label looking](https://i.gyazo.com/e0e5c28aae72c1f71c863e66d5311111.png)

<b>And second</b>
If data-error attribute for label is defined, label itself do not take additional width, so all error message is wrapped. I made small fix for me and I hope it will be implemented in next version

``` CSS
.input-field label {
    width: 100%;
}
```

**Comment by Messier82** [comment]
Made some investigation and done small change in materialize.css file. That's will be the fix for me for now
```CSS
  input[type=text] + label:after, input[type=password] + label:after, input[type=email] + label:after, input[type=url] + label:after, input[type=time] + label:after, input[type=date] + label:after, input[type=datetime-local] + label:after, input[type=tel] + label:after, input[type=number] + label:after, input[type=search] + label:after, textarea.materialize-textarea + label:after {
    display: block;
    content: "";
    position: absolute;
    top: 60px; /*Changed from 65px to 60px for better looking */
    opacity: 0;
    transition: .2s opacity ease-out, .2s color ease-out; }
```
