### ISSUE TITLE
Change scope of CSS for nav menu

### ISSUE THREAD

**Issue by lord-xeon** [Dogfalo/materialize#2576]
Currently, the CSS for the nav is scoped to the HTML element `<nav>`

This makes it very difficult to use the nav element for any other purpose besides the Horizontal Navbar that MateralizeCSS provides.

I want to use much of the other features of MaterialzeCSS, but with a vertical Nav bar.  Semantically, I'd like to use a `<nav>` element with a series of nested `<ul>` tags.  The CSS causes the Nav menu to take on the styles of the horizontal Navbar.

This code is part of the problem:

``` CSS
@media only screen and (min-width: 601px) {
  nav, nav .nav-wrapper i, nav a.button-collapse, nav a.button-collapse i {
    height: 64px;
    line-height: 64px;
  }
  .navbar-fixed {
    height: 64px;
  }
}
```

Additionally, this code:

``` CSS
nav ul li {
  transition: background-color .3s;
  float: left;
  padding: 0;
}
```

Causes the list items to be displayed inline as opposed to a standard List Element - vertically.

Both of these issues require either extensive re-writing of the CSS which takes time, or using a different HTML element besides `<nav>`.  I'd like to keep the markup semantic, so I think this is a bug within MaterializeCSS.

This is what's rendered:
![image](https://cloud.githubusercontent.com/assets/1500115/12072503/56e3abfa-b0af-11e5-9a20-b2e363b8ecbc.png)

This is how I would like it to look:
![image](https://cloud.githubusercontent.com/assets/1500115/12072506/81f51afe-b0af-11e5-8507-7c5943a3c4a5.png)
