### ISSUE TITLE
Problem Dropdown menu navbar large ?

### ISSUE THREAD

**Issue by khanhnam99** [Dogfalo/materialize#2665]
how fix  Dropdown menu navbar large ?

![capture](https://cloud.githubusercontent.com/assets/575720/12370424/0083cfa2-bc43-11e5-9d98-89dbbe175879.PNG)
 fix left , right, bottom

**Comment by JimishF** [comment]
You can add static CSS for that 
Try 
```CSS
#dropdown1{
  width:200px!important;
}
```
