### ISSUE TITLE
responsive headlines

### ISSUE THREAD

**Issue by Sajonara** [Dogfalo/materialize#2684]
I liked the idea of having responsive text with the `.flow-text` class, hence I wrote a little ruby script which output the according styles for all the `h1` to `h6` tags as media queries. I used the same 0.024rem difference in each step in the varying queries and to distinguish the margins I used 0.012rem. Here's my code for it. Just in case someone wants to use it. Because right now headlines won't grow or shrink the same amount as the plain text does with `.flow-text`.

``` css
@media only screen and (min-width: 360px) {
.flow-text {font-size: 1.2rem;}
h1 {font-size: 3.72rem;line-height: 110%;margin: 1.86rem 0 1.44rem 0;}
h2 {font-size: 3.08rem;line-height: 110%;margin: 1.54rem 0 1.184rem 0;}
h3 {font-size: 2.44rem;line-height: 110%;margin: 1.22rem 0 0.928rem 0;}
h4 {font-size: 1.8rem;line-height: 110%;margin: 0.9rem 0 0.672rem 0;}
h5 {font-size: 1.16rem;line-height: 110%;margin: 0.58rem 0 0.416rem 0;}
h6 {font-size: 0.52rem;line-height: 110%;margin: 0.26rem 0 0.16rem 0;}
}
@media only screen and (min-width: 390px) {
.flow-text {font-size: 1.224rem;}
h1 {font-size: 3.744rem;line-height: 110%;margin: 1.872rem 0 1.452rem 0;}
h2 {font-size: 3.104rem;line-height: 110%;margin: 1.552rem 0 1.196rem 0;}
h3 {font-size: 2.464rem;line-height: 110%;margin: 1.232rem 0 0.94rem 0;}
h4 {font-size: 1.824rem;line-height: 110%;margin: 0.912rem 0 0.684rem 0;}
h5 {font-size: 1.184rem;line-height: 110%;margin: 0.592rem 0 0.428rem 0;}
h6 {font-size: 0.544rem;line-height: 110%;margin: 0.272rem 0 0.172rem 0;}
}
@media only screen and (min-width: 420px) {
.flow-text {font-size: 1.248rem;}
h1 {font-size: 3.768rem;line-height: 110%;margin: 1.884rem 0 1.464rem 0;}
h2 {font-size: 3.128rem;line-height: 110%;margin: 1.564rem 0 1.208rem 0;}
h3 {font-size: 2.488rem;line-height: 110%;margin: 1.244rem 0 0.952rem 0;}
h4 {font-size: 1.848rem;line-height: 110%;margin: 0.924rem 0 0.696rem 0;}
h5 {font-size: 1.208rem;line-height: 110%;margin: 0.604rem 0 0.44rem 0;}
h6 {font-size: 0.568rem;line-height: 110%;margin: 0.284rem 0 0.184rem 0;}
}
@media only screen and (min-width: 450px) {
.flow-text {font-size: 1.272rem;}
h1 {font-size: 3.792rem;line-height: 110%;margin: 1.896rem 0 1.476rem 0;}
h2 {font-size: 3.152rem;line-height: 110%;margin: 1.576rem 0 1.22rem 0;}
h3 {font-size: 2.512rem;line-height: 110%;margin: 1.256rem 0 0.964rem 0;}
h4 {font-size: 1.872rem;line-height: 110%;margin: 0.936rem 0 0.708rem 0;}
h5 {font-size: 1.232rem;line-height: 110%;margin: 0.616rem 0 0.452rem 0;}
h6 {font-size: 0.592rem;line-height: 110%;margin: 0.296rem 0 0.196rem 0;}
}
@media only screen and (min-width: 480px) {
.flow-text {font-size: 1.296rem;}
h1 {font-size: 3.816rem;line-height: 110%;margin: 1.908rem 0 1.488rem 0;}
h2 {font-size: 3.176rem;line-height: 110%;margin: 1.588rem 0 1.232rem 0;}
h3 {font-size: 2.536rem;line-height: 110%;margin: 1.268rem 0 0.976rem 0;}
h4 {font-size: 1.896rem;line-height: 110%;margin: 0.948rem 0 0.72rem 0;}
h5 {font-size: 1.256rem;line-height: 110%;margin: 0.628rem 0 0.464rem 0;}
h6 {font-size: 0.616rem;line-height: 110%;margin: 0.308rem 0 0.208rem 0;}
}
@media only screen and (min-width: 510px) {
.flow-text {font-size: 1.32rem;}
h1 {font-size: 3.84rem;line-height: 110%;margin: 1.92rem 0 1.5rem 0;}
h2 {font-size: 3.2rem;line-height: 110%;margin: 1.6rem 0 1.244rem 0;}
h3 {font-size: 2.56rem;line-height: 110%;margin: 1.28rem 0 0.988rem 0;}
h4 {font-size: 1.92rem;line-height: 110%;margin: 0.96rem 0 0.732rem 0;}
h5 {font-size: 1.28rem;line-height: 110%;margin: 0.64rem 0 0.476rem 0;}
h6 {font-size: 0.64rem;line-height: 110%;margin: 0.32rem 0 0.22rem 0;}
}
@media only screen and (min-width: 540px) {
.flow-text {font-size: 1.344rem;}
h1 {font-size: 3.864rem;line-height: 110%;margin: 1.932rem 0 1.512rem 0;}
h2 {font-size: 3.224rem;line-height: 110%;margin: 1.612rem 0 1.256rem 0;}
h3 {font-size: 2.584rem;line-height: 110%;margin: 1.292rem 0 1.0rem 0;}
h4 {font-size: 1.944rem;line-height: 110%;margin: 0.972rem 0 0.744rem 0;}
h5 {font-size: 1.304rem;line-height: 110%;margin: 0.652rem 0 0.488rem 0;}
h6 {font-size: 0.664rem;line-height: 110%;margin: 0.332rem 0 0.232rem 0;}
}
@media only screen and (min-width: 570px) {
.flow-text {font-size: 1.368rem;}
h1 {font-size: 3.888rem;line-height: 110%;margin: 1.944rem 0 1.524rem 0;}
h2 {font-size: 3.248rem;line-height: 110%;margin: 1.624rem 0 1.268rem 0;}
h3 {font-size: 2.608rem;line-height: 110%;margin: 1.304rem 0 1.012rem 0;}
h4 {font-size: 1.968rem;line-height: 110%;margin: 0.984rem 0 0.756rem 0;}
h5 {font-size: 1.328rem;line-height: 110%;margin: 0.664rem 0 0.5rem 0;}
h6 {font-size: 0.688rem;line-height: 110%;margin: 0.344rem 0 0.244rem 0;}
}
@media only screen and (min-width: 600px) {
.flow-text {font-size: 1.392rem;}
h1 {font-size: 3.912rem;line-height: 110%;margin: 1.956rem 0 1.536rem 0;}
h2 {font-size: 3.272rem;line-height: 110%;margin: 1.636rem 0 1.28rem 0;}
h3 {font-size: 2.632rem;line-height: 110%;margin: 1.316rem 0 1.024rem 0;}
h4 {font-size: 1.992rem;line-height: 110%;margin: 0.996rem 0 0.768rem 0;}
h5 {font-size: 1.352rem;line-height: 110%;margin: 0.676rem 0 0.512rem 0;}
h6 {font-size: 0.712rem;line-height: 110%;margin: 0.356rem 0 0.256rem 0;}
}
@media only screen and (min-width: 630px) {
.flow-text {font-size: 1.416rem;}
h1 {font-size: 3.936rem;line-height: 110%;margin: 1.968rem 0 1.548rem 0;}
h2 {font-size: 3.296rem;line-height: 110%;margin: 1.648rem 0 1.292rem 0;}
h3 {font-size: 2.656rem;line-height: 110%;margin: 1.328rem 0 1.036rem 0;}
h4 {font-size: 2.016rem;line-height: 110%;margin: 1.008rem 0 0.78rem 0;}
h5 {font-size: 1.376rem;line-height: 110%;margin: 0.688rem 0 0.524rem 0;}
h6 {font-size: 0.736rem;line-height: 110%;margin: 0.368rem 0 0.268rem 0;}
}
@media only screen and (min-width: 660px) {
.flow-text {font-size: 1.44rem;}
h1 {font-size: 3.96rem;line-height: 110%;margin: 1.98rem 0 1.56rem 0;}
h2 {font-size: 3.32rem;line-height: 110%;margin: 1.66rem 0 1.304rem 0;}
h3 {font-size: 2.68rem;line-height: 110%;margin: 1.34rem 0 1.048rem 0;}
h4 {font-size: 2.04rem;line-height: 110%;margin: 1.02rem 0 0.792rem 0;}
h5 {font-size: 1.4rem;line-height: 110%;margin: 0.7rem 0 0.536rem 0;}
h6 {font-size: 0.76rem;line-height: 110%;margin: 0.38rem 0 0.28rem 0;}
}
@media only screen and (min-width: 690px) {
.flow-text {font-size: 1.464rem;}
h1 {font-size: 3.984rem;line-height: 110%;margin: 1.992rem 0 1.572rem 0;}
h2 {font-size: 3.344rem;line-height: 110%;margin: 1.672rem 0 1.316rem 0;}
h3 {font-size: 2.704rem;line-height: 110%;margin: 1.352rem 0 1.06rem 0;}
h4 {font-size: 2.064rem;line-height: 110%;margin: 1.032rem 0 0.804rem 0;}
h5 {font-size: 1.424rem;line-height: 110%;margin: 0.712rem 0 0.548rem 0;}
h6 {font-size: 0.784rem;line-height: 110%;margin: 0.392rem 0 0.292rem 0;}
}
@media only screen and (min-width: 720px) {
.flow-text {font-size: 1.488rem;}
h1 {font-size: 4.008rem;line-height: 110%;margin: 2.004rem 0 1.584rem 0;}
h2 {font-size: 3.368rem;line-height: 110%;margin: 1.684rem 0 1.328rem 0;}
h3 {font-size: 2.728rem;line-height: 110%;margin: 1.364rem 0 1.072rem 0;}
h4 {font-size: 2.088rem;line-height: 110%;margin: 1.044rem 0 0.816rem 0;}
h5 {font-size: 1.448rem;line-height: 110%;margin: 0.724rem 0 0.56rem 0;}
h6 {font-size: 0.808rem;line-height: 110%;margin: 0.404rem 0 0.304rem 0;}
}
@media only screen and (min-width: 750px) {
.flow-text {font-size: 1.512rem;}
h1 {font-size: 4.032rem;line-height: 110%;margin: 2.016rem 0 1.596rem 0;}
h2 {font-size: 3.392rem;line-height: 110%;margin: 1.696rem 0 1.34rem 0;}
h3 {font-size: 2.752rem;line-height: 110%;margin: 1.376rem 0 1.084rem 0;}
h4 {font-size: 2.112rem;line-height: 110%;margin: 1.056rem 0 0.828rem 0;}
h5 {font-size: 1.472rem;line-height: 110%;margin: 0.736rem 0 0.572rem 0;}
h6 {font-size: 0.832rem;line-height: 110%;margin: 0.416rem 0 0.316rem 0;}
}
@media only screen and (min-width: 780px) {
.flow-text {font-size: 1.536rem;}
h1 {font-size: 4.056rem;line-height: 110%;margin: 2.028rem 0 1.608rem 0;}
h2 {font-size: 3.416rem;line-height: 110%;margin: 1.708rem 0 1.352rem 0;}
h3 {font-size: 2.776rem;line-height: 110%;margin: 1.388rem 0 1.096rem 0;}
h4 {font-size: 2.136rem;line-height: 110%;margin: 1.068rem 0 0.84rem 0;}
h5 {font-size: 1.496rem;line-height: 110%;margin: 0.748rem 0 0.584rem 0;}
h6 {font-size: 0.856rem;line-height: 110%;margin: 0.428rem 0 0.328rem 0;}
}
@media only screen and (min-width: 810px) {
.flow-text {font-size: 1.56rem;}
h1 {font-size: 4.08rem;line-height: 110%;margin: 2.04rem 0 1.62rem 0;}
h2 {font-size: 3.44rem;line-height: 110%;margin: 1.72rem 0 1.364rem 0;}
h3 {font-size: 2.8rem;line-height: 110%;margin: 1.4rem 0 1.108rem 0;}
h4 {font-size: 2.16rem;line-height: 110%;margin: 1.08rem 0 0.852rem 0;}
h5 {font-size: 1.52rem;line-height: 110%;margin: 0.76rem 0 0.596rem 0;}
h6 {font-size: 0.88rem;line-height: 110%;margin: 0.44rem 0 0.34rem 0;}
}
@media only screen and (min-width: 840px) {
.flow-text {font-size: 1.584rem;}
h1 {font-size: 4.104rem;line-height: 110%;margin: 2.052rem 0 1.632rem 0;}
h2 {font-size: 3.464rem;line-height: 110%;margin: 1.732rem 0 1.376rem 0;}
h3 {font-size: 2.824rem;line-height: 110%;margin: 1.412rem 0 1.12rem 0;}
h4 {font-size: 2.184rem;line-height: 110%;margin: 1.092rem 0 0.864rem 0;}
h5 {font-size: 1.544rem;line-height: 110%;margin: 0.772rem 0 0.608rem 0;}
h6 {font-size: 0.904rem;line-height: 110%;margin: 0.452rem 0 0.352rem 0;}
}
@media only screen and (min-width: 870px) {
.flow-text {font-size: 1.608rem;}
h1 {font-size: 4.128rem;line-height: 110%;margin: 2.064rem 0 1.644rem 0;}
h2 {font-size: 3.488rem;line-height: 110%;margin: 1.744rem 0 1.388rem 0;}
h3 {font-size: 2.848rem;line-height: 110%;margin: 1.424rem 0 1.132rem 0;}
h4 {font-size: 2.208rem;line-height: 110%;margin: 1.104rem 0 0.876rem 0;}
h5 {font-size: 1.568rem;line-height: 110%;margin: 0.784rem 0 0.62rem 0;}
h6 {font-size: 0.928rem;line-height: 110%;margin: 0.464rem 0 0.364rem 0;}
}
@media only screen and (min-width: 900px) {
.flow-text {font-size: 1.632rem;}
h1 {font-size: 4.152rem;line-height: 110%;margin: 2.076rem 0 1.656rem 0;}
h2 {font-size: 3.512rem;line-height: 110%;margin: 1.756rem 0 1.4rem 0;}
h3 {font-size: 2.872rem;line-height: 110%;margin: 1.436rem 0 1.144rem 0;}
h4 {font-size: 2.232rem;line-height: 110%;margin: 1.116rem 0 0.888rem 0;}
h5 {font-size: 1.592rem;line-height: 110%;margin: 0.796rem 0 0.632rem 0;}
h6 {font-size: 0.952rem;line-height: 110%;margin: 0.476rem 0 0.376rem 0;}
}
@media only screen and (min-width: 930px) {
.flow-text {font-size: 1.656rem;}
h1 {font-size: 4.176rem;line-height: 110%;margin: 2.088rem 0 1.668rem 0;}
h2 {font-size: 3.536rem;line-height: 110%;margin: 1.768rem 0 1.412rem 0;}
h3 {font-size: 2.896rem;line-height: 110%;margin: 1.448rem 0 1.156rem 0;}
h4 {font-size: 2.256rem;line-height: 110%;margin: 1.128rem 0 0.9rem 0;}
h5 {font-size: 1.616rem;line-height: 110%;margin: 0.808rem 0 0.644rem 0;}
h6 {font-size: 0.976rem;line-height: 110%;margin: 0.488rem 0 0.388rem 0;}
}
@media only screen and (min-width: 960px) {
.flow-text {font-size: 1.68rem;}
h1 {font-size: 4.2rem;line-height: 110%;margin: 2.1rem 0 1.68rem 0;}
h2 {font-size: 3.56rem;line-height: 110%;margin: 1.78rem 0 1.424rem 0;}
h3 {font-size: 2.92rem;line-height: 110%;margin: 1.46rem 0 1.168rem 0;}
h4 {font-size: 2.28rem;line-height: 110%;margin: 1.14rem 0 0.912rem 0;}
h5 {font-size: 1.64rem;line-height: 110%;margin: 0.82rem 0 0.656rem 0;}
h6 {font-size: 1.0rem;line-height: 110%;margin: 0.5rem 0 0.4rem 0;}
}
@media only screen and (max-width: 360px) {
.flow-text {font-size: 1.2rem;}
h1 {font-size: 3.72rem;line-height: 110%;margin: 1.86rem 0 1.44rem 0;}
h2 {font-size: 3.08rem;line-height: 110%;margin: 1.54rem 0 1.184rem 0;}
h3 {font-size: 2.44rem;line-height: 110%;margin: 1.22rem 0 0.928rem 0;}
h4 {font-size: 1.8rem;line-height: 110%;margin: 0.9rem 0 0.672rem 0;}
h5 {font-size: 1.16rem;line-height: 110%;margin: 0.58rem 0 0.416rem 0;}
h6 {font-size: 0.52rem;line-height: 110%;margin: 0.26rem 0 0.16rem 0;}
}
```
