### ISSUE TITLE
Waves in links navbar doesnt take all the width

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#2724]
When you click in a link in a navbar the wave effect doesnt go all the way of the link but just in the middle of the item of the list (for instance, open the navbar of your website and click on a category you'll see one of many things that made me thing that it's not a serious work) so I've a kind of fix : 
nav > ul > li, nav > ul > li > a {
  left: -40px;
  width: 250px;
}
But could you fix it for real, or explain me how to do if it's already possible to have a proper navbar

**Comment by Thanood** [comment]
I've seen this in a sidebar, but navbar works for me. Plunk: http://plnkr.co/edit/fDo4fBinveiQ1Wc6et7G?p=preview

Did you apply waves to the ```<li>```or ```<a>``´ elements? I did it for ```<li>``` and that seems to work.

Here's a fix for sidenav:
```css
.sidenav li.waves-effect {
  display: block;
}
.sidenav li a:hover {
  background-color: transparent;
  display: inline-block;
  width: 100%;
}
```

As you may see, waves cause elements to be ```display: inline-block;``` but the ```<a>``` elements are inline elements and thus have no width. This may be the reason for
> the wave effect doesnt go all the way of the link but just in the middle of the item

If navbar doesn't work you could try to make the ```<a>``` elements be ```display: inline-block;``` and assign a width of 100%.

**Comment by NitroBAY** [comment]
Here's what I mean 
![image](https://cloud.githubusercontent.com/assets/9869317/12695749/05cc564e-c758-11e5-93cb-ffca39d434a1.png) the waves when one click on a nav doesnt take all the width

**Comment by Thanood** [comment]
That was exactly my problem. Even worse, try titles with fewer characters, f.i. a single word. The navs will be next to each other.

Seeing that, it was the hint I needed to do this:
```css
.sidenav li.waves-effect {
  display: block;
}
.sidenav li a:hover {
  background-color: transparent;
  display: inline-block;
  width: 100%;
}
```

Actually, that's untested as I made sidenav a custom element but it should be the same.
Here is (the original for reference)[https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/src/sidenav/sidenav.css].
