### ISSUE TITLE
Dropdown with material icon arrow not working on IE 11

### ISSUE THREAD

**Issue by felangel** [Dogfalo/materialize#2833]
In order to fix it I had to give both the materialize icon arrow and the dropdown activator elements a display inline-block style

**Comment by yaron-e** [comment]
Can you show how you fixed the problem.

**Comment by chi-bd** [comment]
```css
nav ul a{
    display: inline-block;
}
```
