### ISSUE TITLE
Missing draggable ghost image in radio and checkbox in chrome 48

### ISSUE THREAD

**Issue by scarletsky** [Dogfalo/materialize#2845]
Here is a reproduction.
http://codepen.io/scarletsky/pen/dMypvp

When radio / checkbox is dragging, the ghost image miss.
I found that this is related to the following style:

``` css
/* _radio-buttons.scss  */
[type="radio"]:not(:checked),
[type="radio"]:checked {
      position: absolute;
      left: -9999px;         /* this line */
      opacity: 0;
}

/* _checkboxes.scss  */
[type="checkbox"]:not(:checked),
[type="checkbox"]:checked {
      position: absolute;
      left: -9999px;         /* this line */
      opacity: 0;
}   
```
