### ISSUE TITLE
select-dropdown has text cursor

### ISSUE THREAD

**Issue by Fibrewire** [Dogfalo/materialize#2872]
Weird problem where cursor for the input behind the select drop down appears to show on top of the ul > li

Windows 8
IE 11.0.9600.18205

![untitled-1](https://cloud.githubusercontent.com/assets/2836205/13499730/6bbf1c66-e157-11e5-8e68-5574addd6d87.png)

**Comment by sajjad008** [comment]
+1

**Comment by chi-bd** [comment]
Try this.
```css
<style>
@media all and (-ms-high-contrast:none){
	input.select-dropdown.active{ width: 0; }
}
</style>
```
