### ISSUE TITLE
Card title should support h1..h6 tags

### ISSUE THREAD

**Issue by moshest** [Dogfalo/materialize#2896]
I'm using the following code (jade):

```jade
.card
  .card-contet
    h2.card-title Card title
    p Some content here...
```
Everything works fine but the `h2` top & bottom margins.

We should reset the `h1..h6` margin on `.card-contet` class. Maybe like this:

```scss
.card .card-title {
  font-size: 24px;
  font-weight: 300;
  margin: 0; // <-- add this
}
```
