### ISSUE TITLE
Materialize Card Problem

### ISSUE THREAD

**Issue by ProjectBarks** [Dogfalo/materialize#3129]
**Ok so I have a bunch of cards inside of a container and so I wanted the cards to stack really easily using a multi-column layout; however, it seems to break the animated cards.**

Here is an example using the multi column layout: [link](http://goo.gl/Rrq1BK)

Here is an example not using a multi column layout: [link](http://goo.gl/1GNMW0) _(I know they are much bigger here but its more proof of concept)_

I used mostly code from this: [link](http://codepen.io/TrueNorth/pen/MwVoYp)

The only difference between the two is .card-container:

``` scss
@mixin column-count($ct) {
  -webkit-column-count: $ct;
  -moz-column-count: $ct;
  column-count: $ct;
}

.cards-container {
  -webkit-column-break-inside: avoid;
  page-break-inside: avoid;
  break-inside: avoid;
  .card {
    display: inline-block;
    overflow: hidden;
  }
}

.cards-container {
  @include column-count(2);
}
```

If anyone could explain how to fix this our what I did wrong I would be extremely happy!
