### ISSUE TITLE
Tootip Data-Position Not Working

### ISSUE THREAD

**Issue by KoltonG** [Dogfalo/materialize#314]
**Description:** The Tooltip says it can "... add either top, bottom, left, right on data-tooltip to control the position". However it always defaults to the bottom of the element.

**Expected Result:** The tooltip should present itself in the position specified in the data-position attribute.

**Actual Result:** The Tooltip always shows at the bottom of the element.

**Solution:** After looking at the tooltip code I found that at no point does it take in the attribute data-position. This seems easy enough, I made one for the left side tooltip, you just have to change the tooltip position initially, change the backdrop starting location and voila! Make sure to change the backdrop starting location to guarantee a proper Google Material surface reaction effect that we want coming from the left, right, top, bottom.

Here is the code that I made to get it to work for my project, this is not dynamic or takes in data attributes. Its just your tooltip but statically made for the right position. **The HTML structure has the drop down within the element.**

``` javascript
function tooltipIn() {
  var elem = $(this);
  var tooltip = elem.find('.tooltip');
  var backdrop = elem.find('.backdrop');

  tooltip.css({ display: 'block' })
         .velocity({ opacity: 1, left: '65px'}, { duration: 350, queue: false });

  backdrop.css({ display: 'block' })
          .velocity({opacity:1},{duration: 75, delay: 0, queue: false})
          .velocity({scale: 16}, {duration: 300, delay: 0, queue: false, easing: 'easeInOutQuad'});
};

function tooltipOut() {
  var elem = $(this);
  var tooltip = elem.find('.tooltip');
  var backdrop = elem.find('.backdrop');


  tooltip.velocity(
    {opacity: 0, left: '45px'},{ duration: 225, queue: false, delay: 275 }
  );

  backdrop.velocity(
    {opacity: 0, scale: 1},{duration: 225, delay: 225, queue: false,
     complete:  function(){
            backdrop.css('display', 'none');
            tooltip.css('display', 'none');
            }
  });

};
```

**CSS CODE HERE FOR A RIGTH TOOLTIP**

``` css
.tooltip {
  background-clip: padding-box;
  background-color: transparent;
  border-radius: 2px;
  color: #fff;
  display: none;
  font-size: 1rem;
  height: 1rem;
  left: 55px;
  line-height: 1rem;
  overflow: hidden;
  opacity: 0;
  padding: 10px 8px;
  position: absolute;
  text-align: center;
  top: 6px;
  white-space: nowrap;
}

.backdrop {
  background-color: #323232;
  height: 7px;
  width: 14px;
  left: -5px;
  z-index: -1;
  top: 15px;
  border-radius: 0 14px 14px 0;
  padding: 0;
  transform: scale(1);
  position: absolute;
  display: none;
}
```

**ORIGINAL CODE DOES NOT TAKE INTO ACCOUNT DATA-POSITION FOR THE CSS TOP AND LEFT PROPERTY**

``` javascript
      // Mouse In
      $(this).hover(function(e) {
        e.stopPropagation();
        counter = 0;
        counterInterval = setInterval(function(){
          counter += 50;
          if (counter >= defaults.delay && started == false) {
            started = true
            newTooltip.css({ display: 'block' });

            /***************** HERE IS THE ISSUE LOOK HERE!!! :) ************************/
            newTooltip.css({top: origin.offset().top + origin.outerHeight() + margin,
                  left: origin.offset().left + origin.outerWidth()/2 - newTooltip.outerWidth()/2 });

            // Calculate Scale to fill
            scale_factor = newTooltip.width() / 8;
            if (scale_factor < 8)
              scale_factor = 8;

            newTooltip.velocity({ opacity: 1, marginTop: '+10px'}, { duration: 350, queue: false });
            backdrop.css({ display: 'block' })
            .velocity({opacity:1},{duration: 75, delay: 0, queue: false})
            .velocity({scale: scale_factor}, {duration: 300, delay: 0, queue: false, easing: 'easeInOutQuad'});
          }
        }, 50); // End Interval
```

**Conclusion:** I'd love to see this working because this framework is awesome! I'm using it in my projects now. I tried to rewrite the JS to make it work but I am not that experienced with JS! I'll leave it to the experts to figure it out! Looking forward to the fix! 

**Screenshots to show it issue!**
![screen shot 2014-12-22 at 11 32 06 am](https://cloud.githubusercontent.com/assets/3606121/5526853/92ac23be-89ce-11e4-8c4d-7ff738c16834.png)
