### ISSUE TITLE
Visual improvement for textareas

### ISSUE THREAD

**Issue by quentinHydrobat** [Dogfalo/materialize#3154]
Hi everyone !

I'm using this css in a lot of project : 

``` css
textarea.materialize-textarea.inline {
    padding:0;
}
textarea.materialize-textarea.inline:focus {
    padding:1.6rem 0;
}
```

Then when needed, I add `inline` class to textarea so it look like this :

Normal : 
![1](https://cloud.githubusercontent.com/assets/18415375/15207552/41159dee-1827-11e6-805b-a99bf6de6549.PNG)
Focused : 
![2](https://cloud.githubusercontent.com/assets/18415375/15207660/cf4bfe50-1827-11e6-9825-2802bc95cf01.PNG)

If I didn't use a pull request, it's because i don't know if it's OK with material design charts. So if someone can tell me if it's correct ...

Thanks =)
