### ISSUE TITLE
Full screen modal

### ISSUE THREAD

**Issue by wupadach** [Dogfalo/materialize#3377]

**Comment by acburst** [comment]
can you add some more details. Maybe some references to material design examples. If you want to request a feature giving as much detail as possible helps the process.

**Comment by wupadach** [comment]
appending effect more like [this](http://tympanus.net/Development/FullscreenOverlayStyles/index5.html) 
full screen modal [example](http://codepen.io/ThomasBurleson/full/EjrYgX/)
more specific [example](http://expandjs.com/demo/mat-dialog) (Last one)

**Comment by chi-bd** [comment]
Like this?
```css
<style>
.modal.open{
	width: 100%;
	max-height: 100%;
	height: 100%;
	top: 0 !important;
}
</style>
```

**Comment by kmmbvnr** [comment]
@chi-bd  `.model-content` also need to be tweaked, to move modal-action on bottom

```
.modal-content {
  height: calc(100% - 56px);
}
``` 

And still, the close animation works bad. See http://codepen.io/kmmbvnr/pen/pbVZdJ

**Comment by Native-Coder** [comment]
@wupadach 's second example is epic.

**Comment by fega** [comment]
Moved to feature request board.

**Comment by wouerner** [comment]
Hi boys, my implementation, i and the my team uses this solution:
``` css
 .modal.full {                                                                                                      
      width: 100vw; 
      max-height: 100vh; 
      height: 100vh
  }  
```

the **.full** class is add in all project.
