### ISSUE TITLE
Card Reveal is not working correctly on iOS

### ISSUE THREAD

**Issue by thousight** [Dogfalo/materialize#3595]
My cards should be revealing some content when I click the image or the side button like this. It does work on PC and Android like this:
![alt text](http://i.stack.imgur.com/PEApB.jpg)
However, on iOS devices, the content that's suppose to reveal is shifted to the right like the picture below when I click on the button or image to reveal it:
![alt text](http://i.stack.imgur.com/cjn1L.png)
Can someone tell me why this happens and how to fix it? Thank you!

Code:

``` HTML
<div class="Timeline">
    <!-- Grayline in the middle -->
    <div class="grayLine"></div>
    <!-- Actual Content -->
    <div class="timeline-content">
      <div *ngFor="let data of data; let odd = odd; let even = even">
        <div class="row" style="margin-bottom: 0px">
          <div class="col s12 m6 l4" [ngClass]="{ 'offset-l6 offset-m6 timeline-card-right': odd, 'offset-l2': even }">
            <div class="timeline-pointer">
              <div class="pointer-circle"></div>
            </div>
            <div class="timeline-card card horizontal hoverable">
              <div class="timeline-card-image card-image waves-effect waves-block waves-light">
                <img class="activator" src="...}" >
              </div>
              <div class="timeline-card-content card-content">
                <span class="card-title grey-text text-darken-4" style="line-height: 25px">{{data.organization}}</span>
                <p class="timeline-data-location grey-text text-darken-1" style="margin-top: 5px">{{data.city}}, {{data.state}}</p>
                <p style="margin-top: 5px">{{data.degree}}</p>
              </div>
              <!-- Content to be revealed -->
              <div class="card-reveal" *ngIf="data.desc">
                <i class="timeline-reveal-close material-icons card-title">close</i>
                <div class="timeline-desc">
                  <span class="timeline-card-title card-title" style="line-height: 25px">{{data.organization}}</span>
                  <ul *ngFor="let bullet of data.desc">
                    <li>{{bullet}}</li>
                  </ul>
                </div>
              </div>
              <!-- Button that activates the content to be revealed -->
              <i class="timeline-more-button material-icons activator" *ngIf="data.desc">more_vert</i>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
```

CSS:

``` CSS
.Timeline {
  width: 100%;
  position: relative;
}
.grayLine {
  width: 3px;
  height: 78%;
  background: #bdbdbd;
  margin: 50px 50%;
  position: absolute;
  border-radius: 25px;
}
.card {
  margin: 0.5rem 10px 1rem 12px;
}
/*Timeline card arrows*/
.timeline-card::before {
  position: absolute;
  top: 26px;
  right: -15px;
  display: inline-block;
  border-top: 15px solid transparent;
  border-left: 15px solid #ccc;
  border-right: 0 solid #ccc;
  border-bottom: 15px solid transparent;
  content: " ";
}
.timeline-card::after {
  position: absolute;
  top: 27px;
  right: -14px;
  display: inline-block;
  border-top: 14px solid transparent;
  border-left: 14px solid #fff;
  border-right: 0 solid #fff;
  border-bottom: 14px solid transparent;
  content: " ";
}
.timeline-card-right > .timeline-card::before {
  border-left-width: 0;
  border-right-width: 15px;
  left: -15px;
  right: auto;
}
.timeline-card-right > .timeline-card::after {
  border-left-width: 0;
  border-right-width: 14px;
  left: -14px;
  right: auto;
}
.timeline-card-image {
  width: 30%;
}
.timeline-card-content {
  display: block;
  width: 70%;
}
.timeline-data-location {
  font-style: italic;
}
.timeline-more-button {
  float: right;
  margin-left: auto;
  margin-top: 10px;
  margin-right: 5px;
  cursor: pointer;
}
.timeline-reveal-close {
  float: right;
}
.timeline-pointer {
  float: left;
  margin-top: 2.8rem;
  position: absolute;
  left: 50%;
  margin-left: -6px;
}
.pointer-circle {
  width: 0;
  height: 0;
  border: 7.5px solid #4AA9F5;
  border-radius: 180px;
}
```
