### ISSUE TITLE
How to set scroll bar to table？

### ISSUE THREAD

**Issue by isafe** [Dogfalo/materialize#3650]
How to set scroll bar to table？

**Comment by Kail0** [comment]
Well, it's kind of out of context, but you can add this CSS declaration to table

```css
#table.selector {
  overflow-x: scroll; /*horizontal scroll*/
  overflow-y: scroll; /*vertical scroll*/
}
```
