### ISSUE TITLE
FAB to Toolbar scrolling issue

### ISSUE THREAD

**Issue by ralpho00** [Dogfalo/materialize#3900]
As i have observed while using the FAB to Toolbar component (Awesome work), i have seen a little bit of an issue. While the toolbar is open, when i scroll up/down the toolbar returns to its original form which is the FAB, but then pauses for like a millisecond(it is still noticeable)  somewhere above the toolbar, and then after the pause it returns to its original position. I don't know if this is done intentionally so, please clarify it.

EDIT: 
Another thing i have noticed, i have 4 buttons inside my toolbar and i have a sidebar, when i open it, only 3 button appears, then when i resize my browser to the point where the sidebar hides, which is medium size, 4 buttons magically appears.

EDIT:
I've noticed that the 300px padding that the sidebar requires does not apply to the toolbar. that's why it only shows 3 and when the sidebar hides it shows 4 buttons.

**Comment by acburst** [comment]
Can you post some example code?

**Comment by ralpho00** [comment]
Here:
https://jsfiddle.net/hm5ktpww/

To reproduce the bug, view the page in a size where the fixed sidenav will be shown, when the sidenav is shown, click the fab to toolbar button.

**Comment by champa720** [comment]
Quickfix, update css
https://jsfiddle.net/hm5ktpww/15/

```css
.fixed-action-btn.toolbar.active {
  left: initial !important;
  right: 0px !important;
  width: calc(100% - 300px) !important;
}

@media only screen and (max-width: 992px) {  
  .fixed-action-btn.toolbar.active {
    right: initial !important;
    left: 0px !important;
    width: 100% !important;
  }
}
```
