### ISSUE TITLE
Fixed navbar

### ISSUE THREAD

**Issue by murliatdure** [Dogfalo/materialize#393]
- Looking for some utility class that considers the fixed navbar feature

Simply applying position-fixed is working but the color pallete and all others are getting disturbs.

![image](https://cloud.githubusercontent.com/assets/7137859/5605090/1a11bc58-940e-11e4-9d4f-4ad687831861.png)

**Comment by murliatdure** [comment]
![image](https://cloud.githubusercontent.com/assets/7137859/5605123/412d25c8-9410-11e4-9def-cb4d68619353.png)


.nav-fixed {
	position: fixed;
	z-index: auto !important;
}

Still not working.
Seems to be NAVBAR-FIXED with Material Color Pallete, does't fit !!

**Comment by tmd-uk** [comment]
Try adding this CSS to your custom CSS file:
```CSS
body{
	padding-top: 45px;
}

.nav-fixed{
position: fixed;
right: 0;
left: 0;
z-index: 1030;
}

.nav-fixed {
top: 0;
}

@media (min-width: 768px)
.nav-fixed{
border-radius: 0;
}
```

![Image of Screenshot]
(http://www.thinkmilkdesign.co.uk/assets/img/devscreenshot.jpg)
I have used it time and time again from previous Bootstrap projects and there has been no issues (fingers crossed) I hope it works for you too!
