### ISSUE TITLE
ul:not(.browser-default) rule causing tab indicator problem

### ISSUE THREAD

**Issue by jpozo20** [Dogfalo/materialize#4093]
### Description
When testing a new api I'm developing, I noticed a subtle difference in the tabs indicator bewteen my production and local environment. Locally, I have the v0.97.7 and in production I was using the v0.97.8 via CDN.

It looks like that when there are 5 tabs or more there is a problem with the width and position of the tabs indicator.  Inspecting a little bit I found the difference lies in the way the list items style is configured:

v0.97.7
```css
ul {
	padding:0;
	list-style-type:none
}
ul.browser-default,ul.browser-default li {
	list-style-type:initial
}
ul li {
	list-style-type:none
}
```
but in v0.97.8

```css
ul:not(.browser-default) {
	padding-left:0;
	list-style-type:none
}
ul:not(.browser-default) li {
	list-style-type:none
}
```

### Repro Steps
These two images show the tabs indicator working locally with the v0.97.7

![working-1](https://cloud.githubusercontent.com/assets/9166182/21882052/2d76c902-d87f-11e6-89e2-7e3cee558010.png)

![working-2](https://cloud.githubusercontent.com/assets/9166182/21882051/2d764996-d87f-11e6-852e-5feaade0005b.png)

Now these following images are using the v0.97.8

![1](https://cloud.githubusercontent.com/assets/9166182/21882116/6d3fadd8-d87f-11e6-8b48-486e2061298c.png)

![2](https://cloud.githubusercontent.com/assets/9166182/21882115/6d3f1e7c-d87f-11e6-9b88-27f299462b53.png)

![3](https://cloud.githubusercontent.com/assets/9166182/21882114/6d3e66b2-d87f-11e6-9e58-0b4c78687b3c.png)

As you see, there seems to be a problem with the tab indicator everywhere there are tabs.
Also notice the "Discography" tab is present too, but somehow it's getting pushed out of the frame and looking on the inspector tells me it's actually under the first tab though not visible and not selectable.
Although I'm using Firefox on the screenshots, the problem appears in Chrome too.

### Examle code
I just have a simple list of tabs:

```html
<div class="row entry-form">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s2"><a href="#general-tab">General</a></li>
                <li class="tab col s2"><a href="#story-tab" class="active">Story</a></li>
                <li class="tab col s2"><a href="#slogan-tab">Slogan</a></li>
                <li class="tab col s2"><a href="#nicknames-tab">Nicknames</a></li>
                <li class="tab col s2"><a href="#contacts-tab">Contacts</a></li>
                <li class="tab col s2"><a href="#images-tab">Images</a></li>
                <li class="tab col s2"><a href="#discography-tab">Discography</a></li>
            </ul>
        </div>
```
