### ISSUE TITLE
Compact buttons

### ISSUE THREAD

**Issue by gewisser** [Dogfalo/materialize#4146]
### Description
Please add to the class styles:
```css
.compact {
    padding: 0 0.7rem;
}
```
Adding class to the buttons, you can make them smaller

### Repro Steps

Demonstrate issue. https://jsfiddle.net/ak5yuf00/12/
