### ISSUE TITLE
Blinking cursor in Select on IE11

### ISSUE THREAD

**Issue by stsje** [Dogfalo/materialize#4413]
Focusing a Select in IE11 will add a blinking cursor that is visible through the dropdown.

Bug can be reproduced using the selects in the documentation http://materializecss.com/forms.html

Any CSS fix for this?

**Comment by DanielRuf** [comment]
Try the following CSS code and let me know if this fixes your problem.
```CSS
input.select-dropdown:focus {
    text-indent: -9999999em;
}
```
