### ISSUE TITLE
valign/valign-wrapper doesn't work properly (!)

### ISSUE THREAD

**Issue by NonameSLdev** [Dogfalo/materialize#4451]
### Description
`valign-wrapper` class is suppose to only align children with the `valign` class. What it actually does is switch itself into a vertical view along with all the elements in it.
A `valign-wrapper` with 1 element that has the `valign` class also doesn't do anything.
The problem will become more clean in the codepen.

### Screenshots / Codepen
http://codepen.io/NonameSL/pen/XMoroE

**Comment by DanielRuf** [comment]
@NonameSLdev the codepen link seems to be wrong.

The helper does this:
```CSS
// Positioning
.valign-wrapper {
  display: flex;
  align-items: center;

  .valign {
    display: block;
  }
}
```
