### ISSUE TITLE
Variable $button-font-size only applies to icons inside .btn

### ISSUE THREAD

**Issue by Gorzas** [Dogfalo/materialize#4492]
### Description
If you override on _variables.scss the value of $button-font-size it only applies to the icons inside a button but it doesn't applies the change on the text inside.

### Repro Steps
You can see an example on this [Codepen](http://codepen.io/Gorzas/pen/wJZpPd). The code on the SCSS it's a representation of the file [_buttons.scss](https://github.com/Dogfalo/materialize/blob/f4693a9917df7c40e68f380142110f5c4952cef2/sass/components/_buttons.scss#L42-L53) of the library.

### Screenshots / Codepen
An example of the view when you change the value of $button-font-size to .5rem. The icon gets smaller but the text not.
![screenshot from 2017-04-05 12-53-53](https://cloud.githubusercontent.com/assets/1456562/24702456/16765c06-19ff-11e7-8816-fae994c1f507.png)

**Comment by DanielRuf** [comment]
Should be probably

```CSS
.btn,
.btn-floating,
.btn-large,
.btn-flat {

  outline: 0;
  font-size: $button-font-size;
  line-height: inherit;
  }
}
```
or similar.
