### ISSUE TITLE
HTML tag <hr> style

### ISSUE THREAD

**Issue by carusogabriel** [Dogfalo/materialize#4598]
Hello

Materialize has `.divider` out of the box, but, semantic, would be great to have `<hr>` tags to divider the page content. Following the [Material Design Specs for Dividers](https://material.io/guidelines/components/dividers.html), is interesting to make a PR of that?

```css
hr {
    margin-top: 20px;
    margin-bottom: 20px;
    border: 0;
    border-top: 1px solid color("grey", "lighten-2");
}
```
