### ISSUE TITLE
i want to change the color on select dropdown How i can do that, in stackoverflow there  is not good answer

### ISSUE THREAD

**Issue by atlabiz** [Dogfalo/materialize#4644]
### Description
Add a detailed description of your issue.

### I try this, but is not working
```css
/* select css*/
.dropdown-content li > a, .dropdown-content li > span {
    color: #fb8c00 !important;
}
```

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by DanielRuf** [comment]
Please fill out the codepen.

**Comment by tomscholz** [comment]
You can use [the sass version of materialize](http://materializecss.com/sass.html) to customize all the colors.

**Comment by atlabiz** [comment]
can you show me an example how to use it with sass, i dont know this is why i ask,

**Comment by smileytechguy** [comment]
@atlabiz I used the following and it works fine:
```css
.dropdown-content li > a, .dropdown-content li > span {
    color: rgb(245, 124, 0);
}
```
Where `rgb(245, 124,0);` is the color you want
