### ISSUE TITLE
Can't change tab text nor underline color

### ISSUE THREAD

**Issue by newmanw** [Dogfalo/materialize#485]
How do you change a tab bar text and underline color?

**Comment by acburst** [comment]
added to Sass variables in e837e79bdcc46a2ded5d125e2e55d60159ad6c27

**Comment by alanjames1987** [comment]
It would be great to be able to change the underline color with HTML, like we can with other elements.

**Comment by BrenoMazieiro** [comment]
Just use <div class="indicator orange" style="z-index:1"></div> before </ul>

**Comment by BrenoMazieiro** [comment]
Just use
div class="indicator orange" style="z-index:1" /div
before the
/ul

**Comment by Nexxado** [comment]
this worked for me:
override in your css file the following rule:

```css
.tabs .indicator {
    color: <ur color>;
}
```

**Comment by saadq** [comment]
^ The above worked for me to change the tab's underline color, but I had to use `background-color`:

```css
.tabs .indicator {
    background-color: <ur color>;
}
```

**Comment by joaosardinha** [comment]
Neither of these is working here.

**Comment by cande1gut** [comment]
@joaosardinha did you put !important after the color? 

`.tabs .indicator {
    color: <ur color> !important;
}`

**Comment by jamiewaese** [comment]
saadq's answer works perfectly. To be clear, however:
`.tabs .indicator {
    background-color: #99cc00;
}`
The <ur color> needs to be an actual color, without the <> symbols
I needed to do a force refresh before seeing the change.

**Comment by g5codyswartz** [comment]
Building onto @BrenoMazieiro so that his code is readable

Add this right before the `</ul>`
```
<div class="indicator orange" style="z-index:1"></div>
```

**Comment by Native-Coder** [comment]
No one has stated how to change the text color? That salmon color is disgusting.

**Comment by Nexxado** [comment]
@Native-Coder 
```CSS
.tabs .tab a.active {
  color: <my-color>;
}

.tabs .tab a:hover {
  color: <my-color>;
}

.tabs .tab a {
  color: <my-color>;
}
```

notice `.active` is not a pseudo class, but an actual class name.

**Comment by benjaminadk** [comment]
combo of things mentioned: 
1. active is indeed a css class here.  my markup is a yellow scheme

```
.tab a.active {
  color:rgb(252, 234, 37)!important;
  background-color:rgb(3, 169, 244)!important;
}
```

2.I add the indicator and "color of your choice" classes AFTER the <ul>

```
<ul class="tabs tabs-fixed-width light-blue">
                   <div class="indicator yellow" style="z-index:1"></div>
```

I battled with this absolutely heinous pink for a few hours.

**Comment by midgardemon** [comment]
Thanks benjaminadk! puting the div after ul did the trick!

**Comment by hiteshsahu** [comment]
WIth JQuery  
    
 ```
   // TAB Color
    $(".tabs" ).css("background-color", themeColor);

    // TAB Indicator/Underline Color
    $(".tabs>.indicator").css("background-color", '#FFF');

    // TAB Text Color
    $(".tabs>li>a").css("color", '#FFF');
```

where theme color is the color of your choice

**Comment by BenjaminMichael** [comment]
the tab colors can be set with the usual classes red, brown, blue, etc

these were the parts i had to do css to change (thanks to everyone above but nobody had all these put together for me)
```css

.tab a.active {
  color:rgb(252, 234, 37)!important;
  background-color:#448AFF!important;
}
.tabs .tab a:hover {
  background-color: #bcaaa4!important;
  color:#FFFFFF!important;
}
.tabs .tab a {
  color: #efebe9!important;
}
.tabs .indicator{
  background-color:#FFFFFF!important;
}
```

**Comment by jonmase** [comment]
Here's a full answer of how to change both text and indicator/underline color using only HTML and the materialize color classes (i.e. no changes to CSS).

To change the text color, just add the text-color classes to the <a> tags, e.g.: 

`<a href="#test1" class="indigo-text text-darken-4">Test 1</a>`

To change the indicator/underline color, you can insert this before the </ul> (originally posted by @BrenoMazieiro, updated by @g5codyswartz):

`<div class="indicator indigo darken-4" style="z-index:1"></div>`

To wrap this up as a complete, 2-tab, example:

```
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s6">
          <a class="active indigo-text text-darken-4" href="#test1">Test 1</a>
        </li>
        <li class="tab col s6">
          <a class="indigo-text text-darken-4" href="#test2">Test 2</a>
        </li>
        <div class="indicator indigo darken-4" style="z-index:1"></div>
      </ul>
    </div>
    <div id="test1" class="col s12">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
  </div>
```

**Comment by JayHoltslander** [comment]
None of these worked well.

Here's how to do it in a way that doesn't involve using jQuery, extra classes, or !important. 
It includes all components and is in SCSS format.

````scss
// TABS COLORS
.tabs {
  .tab {
    a {
      color: purple;
      &.active {color: purple;}
      &:hover {color: purple;}
      &:focus {
        background-color:lime;
        &.active{background-color:lime}
      }
    }
  }
  .indicator {background-color: purple;}
}
````
[Working demo](https://codepen.io/j_holtslander/pen/NBqPqb)
