### ISSUE TITLE
Multiple Select: checkboxes are not centre aligned

### ISSUE THREAD

**Issue by IsmailM** [Dogfalo/materialize#5083]
The checkboxes in the multiple select are not aligned with the text.

See below of a screenshot of the docs page:

![forms_-_materialize](https://user-images.githubusercontent.com/5578375/29039664-16e3ff98-7ba4-11e7-8d89-937b350b70ef.png)

Potential Fix:

```css
.input-field .dropdown-content [type="checkbox"]+label {
  top: 0; /* previously 1px; */
  display: inline; /* previously inherits `display: inline-block;` from `[type="checkbox"]+label` */
}
```

**Comment by briancwald** [comment]
Yeah, I have this same problem too. your solution seems OK for me, though you won't want to add .col on .input-field as not all input-fields are bound to a grid column.

**Comment by SerdarN92** [comment]
@IsmailM your solutions works for me. Thank you!

**Comment by seabrus** [comment]
@IsmailM I use your solution in a Meteor project, thank you. However, I've modified it a little:
```css
.input-field .dropdown-content [type="checkbox"]+label {
  top: -11px !important; /* previously 1px; */
 }
```
