### ISSUE TITLE
Long lists in SideNav are hiding the last item in Firefox >= 53

### ISSUE THREAD

**Issue by antoniom** [Dogfalo/materialize#5099]
As per title, when rendering a long list on a side nav in Firefox (version 53 or later) it is hiding the last item. Take a look at this codepen: https://codepen.io/abalasas/pen/yoXQby

## Expected Behavior
When viewing the above codepen on firefox 53, Item 1 to Item 20 should be visible.

## Current Behavior
Only Item 1 to Item 19 is visible.

## Possible Solution
Firefox 53 dropped support for -moz-calc. As a consequence the height property inside `.side-nav` is ignored and get the `calc(100% + 60px)` value
```css
.side-nav {
   ...
    height: 100%;
    height: calc(100% + 60px);
    height: -moz-calc(100%); //Temporary Firefox Fix
   ...
}
```
A workaround to the problem could be to write a [Firefox specific rule](https://css-tricks.com/snippets/css/css-hacks-targeting-firefox/) i.e.
```css
@-moz-document url-prefix() { 
  .side-nav {
    height: 100%;
  }
}
```

## Your Environment
* Version used: Latest (0.100.1)
* Browser Name and version: Firefox 54
* Operating System and version (desktop or mobile): Checked on Windows, Mac and Linux (CentOS)
