### ISSUE TITLE
parent table style affects datepicker calendar style

### ISSUE THREAD

**Issue by troncomputers** [Dogfalo/materialize#5190]
Hi.
[CodePen](https://codepen.io/anon/pen/WZbajw)
I put datepicker outside table and everything is fine with calendar.
How to reset child table style to not inherits from parent?

**Comment by storm1er** [comment]
In your css
```css
#formatka tr {border:solid 1px black;font-size:12px}
#formatka td {border:solid 1px black;font-size:12px}
```
You should be more precise by using `>` for example.
