### ISSUE TITLE
_sideNav.scss firefox -moz-calc height no longer supported

### ISSUE THREAD

**Issue by friek108** [Dogfalo/materialize#5196]
In line 10 of `_sideNav.scss`, there is this line for firefox fixes to make sure the of a side nav menu is shown:

    height: -moz-calc(100%); //Temporary Firefox Fix

However, since January, the -moz-calc is no longer supported in firefox so this temporary fix doesn't work anymore. See  https://www.fxsitecompat.com/en-CA/docs/2017/moz-calc-has-been-removed/

**Comment by friek108** [comment]
As a temporary hack / fix (although this doesn't fix the original issue), you could add this css below the `.sideNav.scss`

    @-moz-document url-prefix() {
        .side-nav {
          height: 100%
        }
    }

**Comment by huww98** [comment]
Inspired by https://www.brunildo.org/test/overscrollbackV.html, I have came up with a hick

````css
.side-nav>*:last-child{
    position: relative;
}

.side-nav>*:last-child::after {
    content: ' ';
    background-color: green;
    height: 60px;
    width: 100%;
    position: absolute;
    top: 100%;
    left: 0;
}
````

**Comment by huww98** [comment]
[this line](https://github.com/Dogfalo/materialize/blob/75e95790039e210694291a42615bb41791e864d9/sass/components/_sidenav.scss#L10) can also course problem when used with cssnano.

To demostrate this:
````css
.side-nav {
  height: 100%;
  height: calc(100% + 60px);
  height: -moz-calc(100%);
}
````

This code will be minified as `.side-nav{height:calc(100% + 60px);height:100%}`, which will cause `100%` to override `calc(100% + 60px)`. This will cause Chrome to show an extra 60px padding at bottom.

![image](https://user-images.githubusercontent.com/15710934/33063731-4bd982b2-cede-11e7-9997-0a257809302a.png)
