### ISSUE TITLE
Responsive hiding

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#526]
```css
.hidden 
{
    display: none;
}

@media only screen and (max-width: 600px)
{
    .s-hide, s0
    {
        display: none;
    }
}

@media only screen and (min-width: 601px) and (max-width: 992px)
{
    .m-hide, m0 
    {
        display: none;
    }
}

@media only screen and (min-width: 993px)
{
    .l-hide, l0 
    {
        display: none;
    }
}
```
