### ISSUE TITLE
SideNav should have active element on <a> not <li>

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#5284]
Currently sidenav is implemented in the following way:
```css
.side-nav li.active {
    background-color: rgba(0, 0, 0, 0.05);
}
```
However, typically people set the active element on an <a> tag. For example, when using this in angular, the routerLink directive is usually set on the <a> tag. Setting on li is acceptable, but what is the reasoning behind putting the active class on `li`?

The `a` tag fills the entire `li` so it should be the same outcome, but easier for people to implement with dynamic js frameworks.

## Proposed change
```css
.side-nav a.active {
    background-color: rgba(0, 0, 0, 0.05);
}
```
