### ISSUE TITLE
".dropdown-content li" should not have "text-transform: none"

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#5320]
The following CSS in [_dropdown.scss](https://github.com/Dogfalo/materialize/blob/master/sass/components/_dropdown.scss#L22) is counter-productive. It provides no benefit and introduces a challenge:

```css
.dropdown-content li {
    clear: both;
    color: rgba(0, 0, 0, 0.87);
    cursor: pointer;
    min-height: 50px;
    line-height: 1.5rem;
    width: 100%;
    text-align: left;
    text-transform: none; // <--- this makes no sense
}

```

This prevents applying a text-transformation such as Capitalize to anything in the button's dropdown. For example:

```css
      #profile-dropdown {
         text-transform: capitalize;
         min-width: 200px; 
      }
```

The `text-transform` property would be overridden by `none`, defaulting it to the way the text was input in the html. In the case that data is loaded from the server, then we cannot Capitalize or Uppercase any loaded data, without needlessly using `!important` which is reserved for last resort and special use cases.

## Proposed solution
remove `text-transform: none` from the class specified above
