### ISSUE TITLE
Sidenav items should support longer text

### ISSUE THREAD

**Issue by theakshaydhiman** [Dogfalo/materialize#5760]
## Current Behavior
Sidenav items do not support the longer text. The remaining text is hidden.

## Possible Solution
Here's how I fixed it. You may find a more elegant solution.

Instead of using `li` tags like this: 

```html
<li><a href="#!">Super long text 1</a></li>
<li><a href="#!">Super long text 2</a></li>
```

I used `div` tags:

```html
<div class="sidenav-item"><a href="#!">Super long text 1</a></div>
<div class="sidenav-item"><a href="#!">Super long text 2</a></div>
```

`.sidenav-item` here is:

```css
.sidenav-item a {
    color: #000000de;
    font-weight: 600;
    line-height: 1.5em;
    padding: 10px 32px;
}
```

## Environment
* Version used: 1.0.0-alpha.4
* Browser Name and version: Chrome 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 64-bit, Android 7.1.2
* Link to your project (if appropriate): https://easique.com/mens-style-tips
