### ISSUE TITLE
Responsive Tag Video

### ISSUE THREAD

**Issue by carbos10** [Dogfalo/materialize#606]
I've a video in tag <video> and i would it responsive and insert int in a <div class="row"> but i see on documentation of materialize and <div class="video-container"> is for only iframe, how i could do?

**Comment by RaSeR** [comment]
In css responsive-video hardcoded only for iframe, object, embed, but still got no video tag. So for now you can use this:
```css
.video-container video {
position: absolute;
top: 0;
left: 0;
width: 100%;
height: 100%;
}
```

Hope it works for you.
