### ISSUE TITLE
Change Scss colors to CSS variables

### ISSUE THREAD

**Issue by luxarts** [Dogfalo/materialize#6121]
Hello!

I was trying to change the default colors of the CSS and I saw that you can do it using the Scss, make the changes and compile it. It's a good solution but require install Sass and compile the file every time you want to change the colors so here is an alternative solution:

Instead of hardcoding the colors for the default theme you can use CSS variables and store the colors on it.
Example:
```css
:root{
  --color_primary: #FF0000;
  --color_secondary: #00FF00;
  --color_textOnPrimary: #FFF;
  --color_textOnSecondary: #000; 
}
body{
  background: var(--color_primary);
  color: var(--color_textOnPrimary);
}
```
Maybe the size it's a few kbytes bigger but would be a lot easier at least when the project is in developing stage.

Regards,
Lucas
