### ISSUE TITLE
Clearfix class helpers

### ISSUE THREAD

**Issue by khalyomede** [Dogfalo/materialize#6271]
The code below is a proposal to bring clear fix classes. 

Like in Bootstrap 3 & 4, they are very useful when using the grid. 

I personnaly use the proposal below on one of my project. I think this provides a great way to control how the divs are positioned in the grid.

**Proposal**

```html
<!-- ... grid items ... -->
<div class="clear-xl"></div>
<div class="clear-l"></div>
<div class="clear-m"></div>
<div class="clear-s"></div>
<!-- ... grid items ... -->
```

**Code (SASS free)**

```css
.clear-xl {
	clear: none;
}

.clear-l {
	clear: none;
}

.clear-m {
	clear: none;
}

.clear-s {
	clear: none;
}

@media screen and (max-width: 600px) {
	.clear-s {
		clear: both;
	}
}

@media screen and (min-width: 601px) and (max-width: 992px) {
	.clear-m {
		clear: both;
	}
}

@media screen and (min-width: 993px) and (max-width: 1200px) {
	.clear-l {
		clear: both;
	}
}

@media screen and (min-width: 1201px) {
	.clear-xl {
		clear: both;
	}
}
```
