### ISSUE TITLE
date picker color

### ISSUE THREAD

**Issue by ijash** [Dogfalo/materialize#6285]
I've read the documentation, but doesn't find anything on how to change the date picker color.

found the answer in:
https://stackoverflow.com/questions/35246411/how-to-change-default-body-color-of-materialize-datetimepicker
but with current version i don't think it's compatible anymore.

is there no implementation on changing the color like:
`<input type="text" class="datepicker teal lighten-2">`

or do i have to edit manually(or add custom css) to override the default css?

thank you.

**Comment by MarcoMancha** [comment]
You have to override the color of the time picker of materialize. You can change the following:
```css
.timepicker-digital-display{
  background-color: #056ea3;
}

.timepicker-close{
  color: #056ea3;
}
```
