### ISSUE TITLE
Add ability to center buttons vertically in navbar

### ISSUE THREAD

**Issue by LKay** [Dogfalo/materialize#632]
It should be possible to center button in navbar. Additionally if class for waves is added it breaks vartical align as the display is no longer ``inline-block``. 

Other issue is when assigning non default color to button it loses ``:hover`` effect.

![navbar](http://cl.ly/image/2b2n1A3a2Q2j/Image%202015-02-06%20at%205.27.08%20pm.png)

**Comment by serkandurusoy** [comment]
:+1:

**Comment by carlosperate** [comment]
As per material guidelines (http://www.google.co.uk/design/spec/layout/structure.html#structure-app-bar) icons are on the left or right depending on functionality, I don't think it follows this philosophy to center them.

**Comment by serkandurusoy** [comment]
I believe he is not talking about *icons* and not about *horizontal* alignment.

He is talking about *buttons* being *vertically* aligned.

**Comment by Dogfalo** [comment]
It wasn't a problem for me, I just added `vertical-align: bottom;`

**Comment by JayHoltslander** [comment]
> It wasn't a problem for me, I just added `vertical-align: bottom;`

That won't work with a `<a class="btn right" href="">Floated</a>`

Here's the (SCSS) fix for anyone looking for it.

````scss
nav {
  .right {
    .btn {
      margin-left: 1em;
    }
  }
  .btn {
    display: inline-block;
    vertical-align: middle;
  }
}
````
