### ISSUE TITLE
Checkbox not working on 1.0.0 css

### ISSUE THREAD

**Issue by panpansh** [Dogfalo/materialize#6428]
Using css file 1.0.0 : not working checkbox
but css file 0.97.1 : working

it's html for jade but same structure as your doc
```html
form(action='#')
        p
            input#test5(type='checkbox')
            label(for='test5') Red
        p
            input#test6(type='checkbox', checked='checked')
            label(for='test6') Yellow
        p
            input#filled-in-box.filled-in(type='checkbox', checked='checked')
            label(for='filled-in-box') Filled in
        p
            input#test7(type='checkbox', checked='checked', disabled='disabled')
            label(for='test7') Green
        p
            input#test8(type='checkbox', disabled='disabled')
            label(for='test8') Brown
```

**Comment by panpansh** [comment]
adding this css from 0.97.1 version working : 
```css
[type="checkbox"] + label {
    position: relative;
    padding-left: 35px;
    cursor: pointer;
    display: inline-block;
    height: 25px;
    line-height: 25px;
    font-size: 1rem;
    -webkit-user-select: none;
    -moz-user-select: none;
    -khtml-user-select: none;
    -ms-user-select: none;
}

[type="checkbox"]:not(:checked), [type="checkbox"]:checked {
    position: absolute;
    left: -9999px;
    visibility: hidden;
}

[type="checkbox"]:checked + label::before {
    top: -4px;
    left: -3px;
    width: 12px;
    height: 22px;
    border-top: 2px solid transparent;
    border-left: 2px solid transparent;
    border-right: 2px solid #26a69a;
    border-bottom: 2px solid #26a69a;
    -webkit-transform: rotate(40deg);
    -moz-transform: rotate(40deg);
    -ms-transform: rotate(40deg);
    -o-transform: rotate(40deg);
    transform: rotate(40deg);
    -webkit-backface-visibility: hidden;
    -webkit-transform-origin: 100% 100%;
    -moz-transform-origin: 100% 100%;
    -ms-transform-origin: 100% 100%;
    -o-transform-origin: 100% 100%;
    transform-origin: 100% 100%;
}

[type="checkbox"] + label::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 18px;
    height: 18px;
    z-index: 0;
    border: 2px solid #5a5a5a;
    border-radius: 1px;
    margin-top: 2px;
    -webkit-transition: 0.2s;
    -moz-transition: 0.2s;
    -o-transition: 0.2s;
    -ms-transition: 0.2s;
    transition: 0.2s;
}
```
