### ISSUE TITLE
Unable to change input text color

### ISSUE THREAD

**Issue by tbhaxor** [Dogfalo/materialize#6484]
## Expected Behavior

Change input color to Black

## Current Behavior
default green color

## Possible Solution

`NIL`

## Steps to Reproduce (for bugs)

1.
2.

### CSS
```css
/* label color */
.input-field label {
  color: #000;
}
/* label focus color */
.input-field input[type="text"]:focus + label {
  color: #000;
}
/* label underline focus color */
.input-field input[type="text"]:focus {
  border-bottom: 1px solid #000;
  box-shadow: 0 1px 0 0 #000;
}
/* valid color */
.input-field input[type="text"].valid {
  border-bottom: 1px solid #000;
  box-shadow: 0 1px 0 0 #000;
}
/* invalid color */
.input-field input[type="text"].invalid {
  border-bottom: 1px solid #000;
  box-shadow: 0 1px 0 0 #000;
}
/* icon prefix focus color */
.input-field .prefix.active {
  color: #000;
}
```

### HTML
```html
<div class="container">
    <form action="" method="post">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-title">Contact Us</div>
                        <br>
                        <div class="row">
                            <div class="input-field col s6">
                                <input name="name" id="name" type="text" autofocus>
                                <label for="name">Name</label>
                            </div>
                            <div class="input-field col s6">
                                <input name="email" id="email" type="email">
                                <label for="email">Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="name" id="subject" type="text">
                                <label for="subject">Subject</label>
                            </div>
                        </div>
                        <div class="row">
                            <form class="col s12">
                                <div class="input-field col s12">
                                    <textarea id="textarea1" name="message" class="materialize-textarea"></textarea>
                                    <label for="textarea1">Message</label>
                                </div>
                            </form>
                        </div>
                        <div class="row">
                            <div class="col s12">
                                <button class="btn waves-effect black btn-block waves-light" type="submit" name="action">Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
```

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Firefox 70.0.1
* Operating System and version (desktop or mobile): Manjaro
* Link to your project (if appropriate): Private Project
