### ISSUE TITLE
How to make always bottom footer?

### ISSUE THREAD

**Issue by tthanh** [Dogfalo/materialize#713]
I'm using materialize for myblog, with some tag only have one article, footer not fixed in bottom of the page. How can I make it?

**Comment by Dogfalo** [comment]
```CSS
body {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}

main {
  flex: 1 0 auto;
}
```
