### ISSUE TITLE
Migrate to a flexbox grid

### ISSUE THREAD

**Issue by lee-40square** [Dogfalo/materialize#771]
Flexbox is the future and it's what Angular uses in angular-material (which to me is a terrible implementation). It would be great to see Materialize be the only other UI framework that uses flexbox. :-)

**Comment by Dogfalo** [comment]
We think in the future this will be a great thing, but from our experience with working with flexbox, the world isn't quite ready for this yet.

**Comment by lee-40square** [comment]
I haven't played much yet with flexbox but I might dive in an see. Angular-material is really painful to work with but I think it's because of their class implementation and lack of documentation, not flexbox itself. Anyway, I love what you guys are doing. Keep up the great work! :+1:

**Comment by Dogfalo** [comment]
It's mainly IE, even in the newer 10+ versions, that has issues with it. Even though it "supports" flexbox, it doesn't adhere well to the w3c specifications which in turn causes problems when trying to maintain cross browser compatibility.

Also thanks for the words of encouragement!

**Comment by lee-40square** [comment]
makes sense. I'll close this issue if that's ok with you. I think you're right. Flexbox is not mature enough.

**Comment by dandv** [comment]
Hey Alvin,

Please reconsider this decision.

Flexbox is the way to go forward. There are [ways to get Flexbox working in IE](http://www.planningforaliens.com/blog/2014/03/11/real-world-flexbox/), and IE8 or older has  very small, and dwindling, market share. The kinds of apps built for a Material Design audience, appear to users who use modern browsers.

The community is looking for a [good framework that uses Flexbox](http://www.reddit.com/r/webdev/comments/32gw4h/why_arent_there_any_good_flexbox_frameworks_ala/).

Let's make Materialize better than Bootstrap, which has [refused to use flexbox](https://github.com/twbs/bootstrap/pull/15721).

**Comment by felixsanz** [comment]
+1

**Comment by xFlatlinex** [comment]
I think you should reconsider this, we need good frameworks that push forward. And I think moving to a flexbox grid is the right step here. That plus jQuery removal are the things will make this framework stand out from the rest, because it still feels like a new bootstrap.

**Comment by khalwat** [comment]
Should look to the future, I'd be interested in adopting Materialize if it was based on Flexbox.  Otherwise, as some have stated, it's just a mildly interesting alternative to Bootstrap.

**Comment by khalwat** [comment]
http://philipwalton.github.io/solved-by-flexbox/

**Comment by dandv** [comment]
In #1230, @Dogfalo said

> We don't plan to add support for IE9 and if this is something that you need, you will have to look elsewhere.

So we'll need to figure out what the Flexbox issues are in IE10+, and come up with workarounds. https://github.com/philipwalton/flexbugs is a great start - a repo listing flexbox bugs and workarounds.

**Comment by cvrebert** [comment]
> Let's make Materialize better than Bootstrap, which has refused to use flexbox.

@dandv That will change in Bootstrap v4: https://twitter.com/getbootstrap/status/610859622153515008

**Comment by dandv** [comment]
Added this as a con to http://www.slant.co/topics/150/viewpoints/19/~what-are-the-best-css-frameworks~materialize, among many great features.

**Comment by cvrebert** [comment]
@dandv Creating an experimental fork to prove that it's feasible would be more productive.

**Comment by acburst** [comment]
We are thinking about adding this as an additional grid option in the future

**Comment by dandv** [comment]
@lee-40square: if Flexbox is not mature enough, can you please remove the mention at http://materializecss.com/footer.html that MaterializeCSS uses flexbox?

**Comment by jcapogna** [comment]
Is there something that prevents using Flexbox along with Materialzie?

**Comment by Dogfalo** [comment]
nope

On Mon, Aug 17, 2015 at 1:44 PM, jcapogna <notifications@github.com> wrote:

> Is there something that prevents using Flexbox along with Materialzie?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/771#issuecomment-131956449>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by jcapogna** [comment]
Well in that case, this doesn't seem like that big of a deal. At least, it's certainly not a reason to not use Materialize.

**Comment by dandv** [comment]
You can probably use Materialize along with Bootstrap as well, but does it make sense?

If I use a flexbox grid system, then the Materialize one is just deadweight. Same if I use flexbox for a proper sticky footer instead of [the Materialize one](http://materializecss.com/templates/starter-template/preview.html).

For what it's worth, [Bootstrap 4 has optional flexbox support](http://v4-alpha.getbootstrap.com/getting-started/flexbox/).

Anyway, please remove the false claim at http://materializecss.com/footer.html that flexbox is used for the sticky footer. It's not. See #1409.

**Comment by eikaramba** [comment]
I would also reconsider this today, nearly one year after the decision. Flexbox support is good nowadays, and even for IE <10 possible.
bootstrap is doing it
foundation is doing it
semantic UI is doing it
...more are doing it (which names i not remember)

**Comment by thebiltheory** [comment]
+1

**Comment by ivanjuras** [comment]
+1 has anything happened with Flexbox as of this date?

**Comment by chintanbanugaria** [comment]
+1

**Comment by kmmbvnr** [comment]
Bootstrap 4 recently drops IE9 support and preraring to use Flexbox only.

**Comment by ixdoodla** [comment]
+1

**Comment by bardiarastin** [comment]
+1

**Comment by robinschoss** [comment]
+1! Is there a working fork of this yet?

**Comment by NitroBAY** [comment]
Sorry but I really think, for all reasons above, that you should do it.
It's an huge deal, it's listed as a reason to not use Materialize in a top of best front-end frameworks. Thus devs (including I) may not use or think about dropping Materialize because of that.
Just saying it, it's obviously up to you.

**Comment by jasonsturges** [comment]
Besides remaining competitive with frameworks listed above, Google's Material Design Lite uses Flexbox.

**Comment by Braed** [comment]
This framework looks awesome, it's a shame that flexbox isn't supported. +1

**Comment by xanview** [comment]
Wow, this doesn't use flexbox? - shame, I guess my search continues!

**Comment by DanielRuf** [comment]
Well, you can always include flexbox classes and it should be not so hard to change the grid using the Sass files.

**Comment by tekamolo** [comment]
Does this finally use a flexbox grid or not yet?

**Comment by DanielRuf** [comment]
No, we do not yet use flexbox for the grid.

**Comment by changhaitravis** [comment]
+1 for flex-box. even namespaced out would be good.

**Comment by Native-Coder** [comment]
Why don't we branch it?

**Comment by Dogfalo** [comment]
We're focused on 1.0 release right now. After that is out, we will add a Flexbox grid.

**Comment by IAMtheIAM** [comment]
In the mean time, you can "easily create your own flexbox based grid, [using Susy3](http://oddbird.net/susy/). You don't need to use the out of the box grids that frameworks provide. For example, I created a 24 column grid:

```scss
/* ===============================================================
 *             GRID: Custom 24-Column Flexbox-Based Susy3 Grid
 * =============================================================== */
.col-1 {
   flex: 1 1 span(1 of 24);
   margin-right: gutter(24); // gutter(24) is equavalent to 1 of the 24 columns

   &.last-col {
      margin-right: 0;
   }
}

.col-2 {
   flex: 1 1 span(2 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-3 {
   flex: 1 1 span(3 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-4 {
   flex: 1 1 span(4 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-5 {
   flex: 1 1 span(5 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-6 {
   flex: 1 1 span(6 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-7 {
   flex: 1 1 span(7 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-8 {
   flex: 1 1 span(8 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-9 {
   flex: 1 1 span(9 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-10 {
   flex: 1 1 span(10 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-11 {
   flex: 1 1 span(11 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-12 {
   flex: 1 1 span(12 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-13 {
   flex: 1 1 span(13 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-14 {
   flex: 1 1 span(14 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-15 {
   flex: 1 1 span(15 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-16 {
   flex: 1 1 span(16 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-17 {
   flex: 1 1 span(17 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-18 {
   flex: 1 1 span(18 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-19 {
   flex: 1 1 span(19 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-20 {
   flex: 1 1 span(20 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-21 {
   flex: 1 1 span(21 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-22 {
   flex: 1 1 span(22 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-23 {
   flex: 1 1 span(23 of 24);
   margin-right: gutter(24);

   &.last-col {
      margin-right: 0;
   }
}

.col-24 {
   flex: 1 1 100%;
   margin: 0;

   &.last-col {
      margin-right: 0;
   }
}

.row, .flex {
   display: flex;
}
```

That can easily be changed to a 12 col grid, 9 col, or any grid that suits your needs. I always use [Susy](http://oddbird.net/susy/) for creating grids no matter what CSS framework I'm using.
