### ISSUE TITLE
Checkmark in IE9

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#800]
Hi,

the checkmark in IE9 isn't rotated:

![image](https://cloud.githubusercontent.com/assets/847540/6438729/39a65606-c0cc-11e4-9fd2-f12a8b20e6df.png)

by adding:
```css
[type="checkbox"]:checked + label:before {
    -ms-transform: rotate(40deg);
}
```

this was fixed for me!
