### ISSUE TITLE
Navbar brand in parallax demo

### ISSUE THREAD

**Issue by chukitow** [Dogfalo/materialize#836]
Apparently the navbar brand is broken

![bug](https://www.dropbox.com/s/460sr7v1ui14swg/navbar%20branch.png?dl=1)

**Comment by danielhickman** [comment]
That is actually a problem that can be solved by changing the font size (it may also be cause by the relative positioning and margins). 

This is the what I appended to my styles.css to make it work with "Material Colorize" and the hamburger menu as seen on the demo.

```css
@media only screen and (max-width: 459px) and (min-width: 397px){
nav .brand-logo {
	font-size: 1.8rem;
}
}
@media only screen and (max-width: 396px) and (min-width: 334px){
nav .brand-logo {
	font-size: 1.5rem;
}
}
@media only screen and (max-width: 333px){
nav .brand-logo {
	font-size: 1rem;
}
}
```
