### ISSUE TITLE
Waves-effect on a card results in it being an inline-block

### ISSUE THREAD

**Issue by danielhickman** [Dogfalo/materialize#880]
I added this to my CSS to prevent cards' `display: block` being overwritten by `.waves-effect`
```css
/* Cards Only */
.card.waves-effect, .card-panel.waves-effect {
	display: block !important;
}
```
