### ISSUE TITLE
Blue Links?

### ISSUE THREAD

**Issue by steelcowboy** [Dogfalo/materialize#917]
On my site, the links in my navbar work just fine unless I'm on a page called "Brew Coffee", then some are blue. See https://steelcowboy.me/brew.php, compare to any other page.
[EDIT] Sorry, I just switched to nginx and apparently only https connections work lol

Btw, thanks for the amazing framework! My site is looking better than ever!

**Comment by Dogfalo** [comment]
Link doesn't work

**Comment by Dogfalo** [comment]
They look like styles you added
```CSS
			body { color: #000000; background-color: #FFFFFF;
			}
			a:link { color: #0000CC; }
			p, address {margin-left: 3em; font-size:1.2em; }
			span {font-size: smaller;}

```
